### ISSUE TITLE
Homepage: 1. Remove "Share Your Work" button

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#34]
Homepage issue.

See [Homepage, 1](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit).

**Comment by NedHenry** [comment]
Hyrax 2 now includes a configuration option to control whether or not the "Share Your Work" button displays on the homepage for users not logged in. I configured it to hide the button in this case. By default, the button still shows up for logged in users who have permission to create any type of work. Let me know if the button should be disabled for everyone.

adaff53782660ebf38b1dd89ab177a31550b538b

**Comment by NedHenry** [comment]
I made a further change to the next version (not yet live on production) which disables this button for all users.
