### ISSUE TITLE
MS 35: Norman O. Brown lectures

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#341]
### Collection Information

Formal collection title: Norman O. Brown Lectures

Collection number: MS 35

Collection description: Audio recordings of lectures by and interviews with Norman O. Brown. 

Link to related finding aid: https://oac.cdlib.org/findaid/ark:/13030/kt6m3nd4kj/

If a collection is being processed by series, formal series titles and numbering (recorded in the order in which the series will be processed): 

### Objects

Type/format and dimensions of objects (within each collection or series) & quantity: 13 audio records

Currently individually cataloged recordings in Alma; all reformatted from tape to CD; believe digital audio files may exist on server
Files: 30 .aif audio files
Collection size: 17 GB
Location of digital files: //artifacts2.library.ucsc.edu/diginit2/ms0035_norman_o_brown/norman_o_brown_audio_MOD

### Rights Information

Copyright statement: Property rights for this work reside with the University of California. Literary rights, including copyright, are retained by the creators and their heirs.   The digital copy of this work is intended to support research, teaching, and private study. The publication or use of any work protected by copyright beyond that allowed by fair use for research or educational purposes requires written permission from the copyright owner. Responsibility for obtaining permissions, and for any use rests exclusively with the user. For more information on copyright or to order an image, please visit   guides.library.ucsc.edu/speccoll/reproduction-publication.

Rights holder: Thomas N. Brown

Access rights: For educational uses only

Rights status (value from RightsStatements.org):

Processing archivist(s): n/a

Section completed by: RJ

## Section 2: Metadata Assessment

Metadata source(s): MARC records

Metadata properties to be included:

masterFilename
title
titleAlternative
creator
contributor
dateDigitized
dateCreated
extent
subjectName
subjectTitle
subjectTopic
description
description
description
language
genre
resourceType
rightsStatement
rightsHolder
accessRights
rightsStatus
publisher
publisherHomepage
itemCallNumber

Metadata specialist(s): RJ

Section completed by: RJ

## Section 3: Digitization/Technical Processing Assessment

File format(s) for preservation masters: aif

File naming conventions: lcd

File directory on Artifacts2: diginit2/ms0035_norman_o_brown/norman_o_brown_audio_MOD

Link to digitization initial assessment worksheet: n/a

Digitization specialist(s): Scott Campbell

## Section 4: File assessment and processing
(This section is commonly used for previously digitized or outsourced digitization projects)

- [x] Master files located and organized on Artifacts

- [x] File quality assessed and standards documented on the digital assessment worksheet

- [x] Files processed if needed

- [x] Filenames matched to metadata spreadsheet

- [x] Files saved on dams_ingest

## Section 6: Display Assessment

Thumbnail Image for DAMS homepage:

## Actions & Acceptance Criteria 
_(workflow specific to each collection, i.e., the steps required to prepare it for ingest)_

### Digital Projects Workflow:
- [x] Collection Information and planning/assessment sections (1-7) completed
- [x] Initial project meeting
- [x] MARC records exported
- [x] Metadata spreadsheet prepared
- [x] Files assessed and prepared for ingest

### Ingest Workflow:
- [ ] Ingest metadata spreadsheet conforms to Bulkrax ingest specification
- [x] Files relocated to dams_ingest 
- [ ] Collection has been successfully ingested
- [ ] Recordings play properly
- [ ] Metadata displays properly
- [ ] Collection has been published and is available to users on DAMS homepage

**Comment by rmjaffe** [comment]
@tmariamora Please select a representative image for this collection.

**Comment by tmariamora** [comment]
Let's use this: https://digitalcollections.library.ucsc.edu/records/1r66j2294

**Comment by rmjaffe** [comment]
This collection still needs to be assigned a value from rightsstatements.org

**Comment by tmariamora** [comment]
It's in copyright: http://rightsstatements.org/vocab/InC/1.0/

**Comment by rmjaffe** [comment]
@snehagunduraoUL the ingest of this collection keeps failing in production.  As you have time, please take a look to see if you can identify the cause. Thanks!

**Comment by snehagunduraoUL** [comment]
Sure. I’ll take a look.

**Comment by rmjaffe** [comment]
@snehagunduraoUL Thanks to you, these are all in production and look good. I updated the visibility to private.  One question for you or @rschwab:  Any thoughts on how easy or hard it might be to reorder the items as they appear in the player?  For example:

![Image](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/32003407/e53d6021-419f-4db9-9691-00146168efc9)

**Comment by rschwab** [comment]
We will need an "order" or "weight" field to properly deal with this issue. So far we've been coding one-off solutions but that isn't sustainable. We could in theory do that here, but I think the sooner we handle this in a systematic way, the better.

**Comment by rmjaffe** [comment]
Roughly speaking would the best way to handle ordering of works in the player as well as child works be to define an order in the ingest spreadsheet, ala https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/383?

**Comment by rschwab** [comment]
Yes, I believe so.
