### ISSUE TITLE
(8) Evaluate ADD Inheritance feature

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#346]
The data dictionary called for a feature called "ADD Inheritance", which would work by adding values from parent works/collections to the existing values already present on the work. The use case is when a field like SubjectName or Genre has values that apply to individual works, in addition to other values that would apply to the whole collection. This feature would allow a metadata librarian to complete an ingest without needing to add the collection-wide values to each constituent work.

It doesn't appear this feature was ever implemented in BulkOps, and doesn't exist in Bulkrax. How feasible is implementing this feature? How does the effort compare to other ways of solving this need?

**Comment by rmjaffe** [comment]
When testing this functionality in sandbox (inheritance_test_RJ), the value entered at the collection level in subjectName was not inherited by the works within the collection or added to whichever values were already assigned at the work level.  For example, in this test load the value, https://id.loc.gov/authorities/names/n79041870 (i.e. Virginia Woolf), was entered in the collection record, but does not appear on the [work records](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/q237hs153?locale=en) as a label or URI.
