### ISSUE TITLE
Homepage: 2. Move "Terms of Use" link to the footer

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#35]
(Terms of use beneath "Share Your Work button.)

See [Homepage, 2](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit).

**Comment by NedHenry** [comment]
Solved in this commit, not yet implemented on the production site

cdf410200201a6e8ad83e0de1d6323cbab01bd5f

**Comment by NedHenry** [comment]
deployed
