### ISSUE TITLE
Homepage: 3. Hide “Featured Works” and “Recently Uploaded” tab navigation

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#36]
(but maintain display of the links/list of courses)

See [Homepage, 3](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit).

**Comment by NedHenry** [comment]
Solved in this commit, not yet deployed on the production site
fa4d5d74e74cdd8fc41b3fd47079eaa8e5534cb6

**Comment by NedHenry** [comment]
deployed
