### ISSUE TITLE
(2) Remove date uploaded and date modified from the sorting options

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#367]
### Descriptive Summary

In [#324](https://github.com/UCSCLibrary/dams_project_mgmt/issues/324#issuecomment-990236497) A-Z sorting and dateCreated sorting was added.

<img width="855" alt="Screen Shot 2022-08-01 at 1 56 17 PM" src="https://user-images.githubusercontent.com/32003407/182245227-61fc0366-577f-4779-940a-417801347dc9.png">

We would like to remove date uploaded and date modified as sorting options.

### Acceptance Criteria

Done means:
- [ ] Date uploaded sorting options removed
- [ ] Date modified sorting options removed

**Comment by rmjaffe** [comment]
Re: QA -- looks good to me!
