### ISSUE TITLE
(x) Determine & update inheritance rule for description field

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#368]
Description does not currently inherit from parent works or collections. From Rachel:
> we'd decided that while we wanted any child works not having descriptions of their own to inherit descriptions from their parent work, we did not want works to inherit descriptions from the collection. So while most of the inheritance rules can be applied without being sensitive to the nature of the hierarchical relationship (collection-works or parent work-child works), description is the outlier. We can talk more, but if it's too much break the rules to provide for this exception, we can probably come up with a satisfactory workaround, for example, in a collection-level description instead of saying "This collection includes photographs ..." we include the formal name of so that the context of the descriptive statement isn't lost when it appears as inherited value in a work record.

**Comment by rmjaffe** [comment]
Related work: [Inheritance seems to be broken #567](https://github.com/UCSCLibrary/dams_project_mgmt/issues/567)
