### ISSUE TITLE
(x) Fields that should not inherit currently are

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#369]
There are several fields which do inherit but should not according to the dictionary: boxFolder, coordinates, physicalDescription, physicalFormat, resourceType, staffNote, and titleAlternative.

**Comment by rmjaffe** [comment]
Related work: [Inheritance seems to be broken #567](https://github.com/UCSCLibrary/dams_project_mgmt/issues/567)
