### ISSUE TITLE
Homepage: 4. Modify “Featured Works” display

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#37]
Remove File Type (eg. “Audio”) and Keywords (eg. “History”)
Display Date Created and Description below object Title
Make course title link to course page

See [Homepage, 4](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit).

**Comment by NedHenry** [comment]
Solved in this commit, not yet deployed on the production site
49ecf54ff2a47df30981cd52c64996a430325989

**Comment by NedHenry** [comment]
deployed
