### ISSUE TITLE
(1) Create new A-Z List of Collections page: Mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#375]
### Descriptive Summary

As an end user, I want to view a complete list of all collections included in the DAMS on my mobile device.

Style mobile page to match:
![AtoZ_Mobile](https://user-images.githubusercontent.com/6412857/79625105-87a2ad80-80db-11ea-8b1d-185650c92403.png)

### Acceptance Criteria
This is what done looks like

* [x] Box with a brief description of the DAMS is included at the top
* [x] Thumbnails for each collection are displayed
* [ ] Description of the collection is hidden
* [x] The title of each collection is linked to the collection's landing page
* [x] Include link to A-Z page on DAMS homepage (refer to UCSCLibrary/dams_project_mgmt#279, UCSCLibrary/dams_project_mgmt#280 for homepage mockups)

### Related work
Mock up ticket: UCSCLibrary/dams_project_mgmt#247 
Desktop ticket: UCSCLibrary/dams_project_mgmt#277 
[Mock up in Google Drive](https://drive.google.com/open?id=1LZCYHTut1TaeU-eGGNOHDNyGxo_BgMtm)

UCSCLibrary/dams_project_mgmt#366 and UCSCLibrary/dams_project_mgmt#324 are prerequisites

**Comment by rschwab** [comment]
Descriptions still need to be hidden for this to be completed.

**Comment by JessWaggs** [comment]
Looks good in mobile prod!
