### ISSUE TITLE
Enable faceting of collections on A-Z page

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#376]
### Descriptive Summary

As an end user, I want to be able to use facets to filter collections by criteria such as subject/topic. 

### Background 

As we continue to add collections to our DAMS, providing users with ways to sort and filter collections will improve user efficiency and effectiveness in finding relevant collections.  Upon reflection, we've determined that while faceting will improve user experience, sorting isn't necessary.

### Acceptance Criteria

This is what done looks like:

* [ ] Users can use facets to filter the collections displayed on the A-Z collections page 

### Related work
#488

**Comment by rmjaffe** [comment]
My sense is that this should be split into two tickets: one for sorting and one for faceting.  As far as sorting, is sorting by date really meaningful or helpful especially as the dateCreated ranges for some of these collections span decades.

**Comment by JessWaggs** [comment]
@rmjaffe I am comfortable eliminating the need for sorting. Sorting by most recent feels like something power users / staff would find more useful. It doesn't feel like a feature that prioritizes student success with these materials.

For the faceting, I can create a mock-up for this. Should I make a new ticket for that mock-up?

**Comment by rmjaffe** [comment]
Thanks @JessWaggs!  I think we can rescope this existing ticket by adding 'create a mock-up' as an acceptance criterion and noting the the background section that we've decided to let go of the sorting component.

**Comment by rmjaffe** [comment]
@JessWaggs And think about this again -- probably best to create a separate mock-up ticket as you'll likely get to that much sooner than we'll be able take on the development work.

**Comment by rmjaffe** [comment]
@JessWaggs Created #488 for creating the mockups.
