### ISSUE TITLE
Homepage: 5. Add text explaining this media site and directing users to the CONTENTdm site for other content

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#38]
Text: “The UC Santa Cruz University Library Digital Media Collection site contains digitized audio and video materials from the Special Collections and Archives department. 
Visit our Digital Collections site for images and oral histories.”

See [Homepage, 5](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit#).

**Comment by NedHenry** [comment]
Completed in this commit: 5bd88d6339ade6fffe6e73626228add1ea848e39
