### ISSUE TITLE
(5) Pagination on A-Z page/About Our Collections in DAMS-staging

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#382]
### Descriptive Summary

During QA of UCSCLibrary/dams_project_mgmt#277 it was observed that the pagination or paging tool at the foot of the A-Z page wasn't working on the staging site.  

<img width="1048" alt="Screen Shot 2021-11-30 at 9 55 15 AM" src="https://user-images.githubusercontent.com/32003407/144101708-2f265cf2-c0cd-4e8d-9598-7bc3e71d042e.png">

When clicking on a page number or on 'next' the system would redirect to an error page.

<img width="861" alt="Screen Shot 2021-11-30 at 9 55 56 AM" src="https://user-images.githubusercontent.com/32003407/144101726-f33983b3-ffe3-4bc3-ab09-9445a4ec3d39.png">

In casually browsing through various collections and search result sets, I am able to successfully page through the results.

Consider using the User Story format:

As a enduser, I would like to be able to successfully page through the collections represented in the A-Z list of collections.

### Acceptance Criteria

This is what done looks like:

* [x] Users are able to successfully page through the contents of the A-Z list (if/when content appears on multiple pages)

### Expected Behavior 

Helpful when reporting bugs to explain the expected behavior 

### Actual Behavior

See above.

### Steps to reproduce 

Visit the [About Our Collections page](https://digitalcollections-staging.library.ucsc.edu/collections) on staging, click a number or next on the pager at the bottom.

### Related Work 

UCSCLibrary/dams_project_mgmt#277
UCSCLibrary/ucsc-library-digital-collections#375

**Comment by rschwab** [comment]
I accidentally pushed this directly into sandbox, so there isn't a pull request. Here's the information that would be on the PR:
- The [code commit](https://github.com/UCSCLibrary/ucsc-library-digital-collections/commit/f58cbffd7a72bb29d62c16a371aaedd6ade2b913)
- Creates a new search builder class that inherits from the Hyrax collection search builder.
- Overrides the add_sorting_to_solr method in the new class.
- Removes alpha sorting from the view code, its now done via the new method.

This work uncovered some oddness with visibility settings, with more details in the pull request linked above this comment.

**Comment by JessWaggs** [comment]
A-Z page pagination in Staging is working for me
