### ISSUE TITLE
Convert https to http before performing authority lookup

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#387]
As a policy, import spreadsheets should always use http instead of https in the URI's of authority headings. The code should provide a fallback conversion in case one slips through.

Also, account for trailing forward slashes (or lack thereof)

**Comment by rschwab** [comment]
I believe this ticket is out-of-date and that these issues have been solved. 
- The URI sanitation described in the ticket is implemented in our local bulkrax processing.
- The resource type field was just updated in my recent PR.
@snehagunduraoUL what do you think?

**Comment by snehagunduraoUL** [comment]
Yes. This has been addressed. We can mark this done.
