### ISSUE TITLE
(2) Determine which collection metadata fields will be keyword searchable

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#389]
### Descriptive Summary
In [collection_indexer.rb](https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/master/app/indexers/collection_indexer.rb) the collection fields are indexed into Solr. We need to decide which fields we want to be indexed as keyword searchable. In a soon-to-be-merged commit, the following fields will be indexed as searchable:
- collectionCallNumber
- extent
- donorProvenance
- publisherHomepage
- rightsStatement
- rightsHolder
- rightsStatus
- accessRights
- subjectName
- subjectPlace
- subjectTopic
- subjectTitle

These fields are indexed, but not searchable:
- dateCreatedDisplay
- harmfulLanguageStatement

### Acceptance Criteria

- [ ] A list of keyword searchable collection fields is identified in this thread.
- [ ] The identified keyword searchable fields are reflected in collection_indexer.rb

**Comment by rmjaffe** [comment]
These decisions should also be documented on the data dictionary.

**Comment by JessWaggs** [comment]
I've added two new columns to the Data Dictionary: Indexed and Searchable

I've updated those two columns to reflect the information in this ticket. I'm sure we have indexed and made searchable properties beyond those listed in this ticket (eg. creator, title), but I wasn't sure how to find that information to make sure I was entering the data correctly.

@rmjaffe @rschwab Would you be able to point me in the right direction for figuring out which other fields are indexed and searchable?

**Comment by rschwab** [comment]
Here's the file that I believe controls those settings: https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/master/config/metadata.yml

If it's stored_in_solr, its indexed.

**Comment by JessWaggs** [comment]
Chatted with Ryan that perhaps Sortable / Faceting / Searchable were the elements to include in the Data Dictionary, as it looks like everything is indexed.

@rmjaffe There are quite a few elements in the yml file that are not in the data dictionary so I just ignored those
