### ISSUE TITLE
Detail and create mock-ups for interim/tier one complex image objects display (option #1)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#395]
### Descriptive Summary

Given the complexity involved in modifying the UV, we've decided to implement a simpler first-pass strategy for updating the display of complex image objects (i.e. parent-child works, not filesets).  In the future, we hope to implement the approach detailed in Apply new child work page (Desktop) UCSCLibrary/ucsc-library-digital-collections#396 and Apply new child works page (Mobile) UCSCLibrary/ucsc-library-digital-collections#397.

For images (e.g. MS 20):
- Duplicate and add the first child work image to the parent metadata record.  
- The complex object landing page should show the first child work image and the parent metadata record, and the first among the child works in the Items list below should be a thumbnail of the first child work image and title for the first child work (which links to the child work show page).

For cartographic material (including aerials):
- Display **only** the metadata record for the parent work on the complex object landing page.  
- The complex object landing page should show only the parent metadata record, and the first among the child works in the Items list below should be a thumbnail of the first child work image and title for the first child work (which links to the child work show page).

The introduction of this interim strategy should not affect the implementation of the search and retrieval recommendations made in Implement New Search & Retrieval Experience for Complex Objects UCSCLibrary/dams_project_mgmt#398.

### Acceptance Criteria

- [ ] TBD

### Related Work
Apply new child work page (Desktop) UCSCLibrary/ucsc-library-digital-collections#396
Apply new child works page (Mobile) UCSCLibrary/ucsc-library-digital-collections#397
New Search & Retrieval Experience for Complex Objects #398

**Comment by rmjaffe** [comment]
@rschwab @JessWaggs Can you give this ticket a read and confirm or correct my understanding of our interim strategy?

@JessWaggs Can you confirm that the statement "The introduction of this interim strategy should not affect the implementation of the search and retrieval recommendations made in Implement New Search & Retrieval Experience for Complex Objects https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/388" is true?

**Comment by rschwab** [comment]
Note #398 is now the ticket for "search & retrieval experience"

**Comment by rmjaffe** [comment]
@JessWaggs is out, so I'm thinking I'll go ahead and bring Update display settings to show child vs. parent metadata record on work display page #541 onto the new board and quarantine it in the 'unassigned' column.  If we're all on the same page about the interim display as it's described on this ticket, I can retire that ticket vice versa.

**Comment by rmjaffe** [comment]
Discussion of complex image objects has been had; closing ticket.
