### ISSUE TITLE
Deprecation warnings in Production error logs

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/ucsc-library-digital-collections#399]
The error logs on the production machine has been collecting deprecation warnings.

App 16639 output: DEPRECATION WARNING: search_field_def_for_key is deprecated and will be removed from blacklight 7.x (Use blacklight_config.search_fields[key]). (called from add_advanced_parse_q_to_solr at /srv/ucsc_sufia/shared/bundle/ruby/2.7.0/gems/blacklight_advanced_search-6.4.1/lib/blacklight_advanced_search/advanced_search_builder.rb:53)

**Comment by rschwab** [comment]
This was resolved many months ago.
