### ISSUE TITLE
Course Pages: 1. Modify Breadcrumbs

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#40]
Modify Breadcrumbs:

1. Preferred Option: Remove “My works” from breadcrumbs and replace with Course page (see image in doc)  OR
2. Alternative option: Remove breadcrumbs entirely

See [Course Pages, 1](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit#bookmark=id.v2bzq6nvpf4c).

**Comment by NedHenry** [comment]
see #49
