### ISSUE TITLE
Silence unnecessary notifications/warnings

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#400]
### Descriptive Summary

On a few occasions we've had issues in our production environment where the logs have been filled up by various warnings, so we've decided to proactively silence notifications/warnigns for things that aren't (as) important.

### Background 

There is an issue that Daniel noticed over the weekend with the production server hard drive filling up. He found the logs were filling with deprecation warnings, and freed up some space to keep everything going.

### Acceptance Criteria

This is what done looks like:

* [ ] Determine appropriate setting to suspend unneeded notifications/warnings
* [ ] Notifications for unimportant things aren't filling the logs!

**Comment by rschwab** [comment]
This was resolved many months ago.
