### ISSUE TITLE
(1)Date Digitized (dateModified) visible only to admin users

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/ucsc-library-digital-collections#401]
### User Story

As an staff member, I want the dateDigitized field values entered on the ingest spreadsheet to display in the metadata records within the DAMS.

As a non staff member, I should not see the dateDigitized field value 

### Background 

Date Digitized values did not match the ingest spreadsheet in DAMS. For instance, the Shakespeare Santa Cruz ingest spreadsheet did not contain dateDigitized properties but a metadata value labeled Date Digitized displays in the DAMS.

Ned investigated further in https://github.com/UCSCLibrary/dams_project_mgmt/issues/89 and found that this is happening because "the Hyrax core metadata property date_modified (which automatically stores the most recent time a record is edited by the Hyrax application) is automatically configured to use the RDF predicated DublinCore/modified, which we also use for our dateDigitized metadata property/" 

He redefined the date_modified property to use a different predicate, which solves the problem so future records should not have their dateDigitized metadata overwritten.

However - All the current records in the system have had their dateDigitized metadata overwritten with the date they were ingested into Hyrax. In the future, they can be updated via roundtripping to show the dates from the ingest spreadsheet.  

### Related Work 

https://github.com/UCSCLibrary/dams_project_mgmt/issues/89

**Comment by rschwab** [comment]
@rmjaffe This one is ready for QA in Sandbox. I put a digitized date on [this work in sandbox](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/cj82k810d?locale=en) for testing, if that's helpful.

**Comment by rmjaffe** [comment]
@rschwab Looks good to me; I think this can move along. Thanks!

Not logged in: No dateDigitized!
![Screen Shot 2023-05-02 at 10 31 46 AM](https://user-images.githubusercontent.com/32003407/235741327-ae27236f-f925-4ff2-99ac-ef771544ede4.png)

Logged in: dateDigitized!
![Screen Shot 2023-05-02 at 10 32 52 AM](https://user-images.githubusercontent.com/32003407/235741357-816e7452-f052-4208-a8d6-e9cd9d7a948b.png)

**Comment by rmjaffe** [comment]
Looks good in production :)

While logged in, dateDigitized displays:
![Image](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/32003407/67ab4566-30f3-489b-a077-9ce8c9a8d7df)

While not logged in, not seeing this value:
![Image](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/32003407/339fa2fb-b539-4b3d-918b-c89b1c3221b5)
