### ISSUE TITLE
(3) Disable translations, forcing English

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#404]
Edit: We've decided on option A, disable translations.

Patron reported this link, with the interface translated to French: https://digitalcollections.library.ucsc.edu/catalog?f%5Bancestor_collection_titles_ssim%5D%5B%5D=UC+Santa+Cruz+Campus+History+Collections&f%5BsubjectTopic_sim%5D%5B%5D=College+teachers&locale=fr&q=Image&search_field=resourceType&sort=system_modified_dtsi+asc

Somehow Google has indexed at least one link in French. We need to decide whether we want to:
A) Disable translations, forcing English
B) Utilize translations, and offer a language switch UI.
C) Something else.

Then implement this decision. As of now users potentially end up on non-English pages with no way to change it back (other than URL editing).

**Comment by rschwab** [comment]
Note: We can set some variables on the Rails internationalization gem to limit the supported languages to English, however this leads to an error page when other locale's are used in the URL. I will undo those changes and instead attempt to redirect non-English traffic back to the English version using htaccess or another server-side redirection method.

**Comment by rmjaffe** [comment]
Thanks for the investigation and update.  I agree -- chasing down every instance where the rewrites are happening doesn't seem like the highest priority use of time.  Likely some serious wishful thinking on my part, but is there any chance this might be resolved with the stack upgrade?

Improving the error message 100% makes sense.  @JessWaggs I'll defer to you as to whether the impact on users is enough that we should continue to chase this rabbit.

**Comment by rschwab** [comment]
Just an FYI, updating the error page is very simple and involves just writing some html+css on [this file](https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/master/public/500.html). Updating the 404 page is the same easy process.

**Comment by rschwab** [comment]
@JessWaggs & @rmjaffe How does this look for an interim error page? 
![Firefox_Screenshot_2023-05-04T23-35-42 023Z](https://user-images.githubusercontent.com/515412/236351791-07fb609b-339d-4e90-ad96-28da6905f55f.png)

**Comment by JessWaggs** [comment]
I'd be in favor of removing the "report this problem" link and just having the "return to homepage" link.

**Comment by rschwab** [comment]
@rmjaffe @JessWaggs This is ready for QA in Sandbox. Changing any "locale=en" to another language code (fr, de, etc) should lead to the error page with a link back home.

**Comment by rmjaffe** [comment]
@rschwab Just looked at a couple random works/pages in sandbox and updated the URLs:

1) http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/v979v3346?locale=en --> http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/v979v3346?locale=de
![Screen Shot 2023-05-09 at 9 41 12 AM](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/32003407/1a39dc53-f1b0-45dd-971e-f8af0e83823a)

2) http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/rj430493h?locale=en -- http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/rj430493h?locale=jp
![Screen Shot 2023-05-09 at 9 41 12 AM](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/32003407/f589cb0f-7ac3-4c8c-8c94-6dd82e4c51d9)

3) http://digitalcollections-staging-sandbox.library.ucsc.edu/collections/kp78gg41b?locale=en --> http://digitalcollections-staging-sandbox.library.ucsc.edu/collections/kp78gg41b?locale=gr
![Screen Shot 2023-05-09 at 9 41 12 AM](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/32003407/8e4889c4-a0db-4079-a099-4effb113ded8)

Seems everything is coming up error pages!  Is weird though -- after I change the language code in the URL and hit enter, it briefly reverts back to "en" before then changing back to whichever language code I entered and serving up the error page.  I think this is good to move forward.

**Comment by JessWaggs** [comment]
Working for me as expected as well!

@rschwab Is it correct that Google will stop indexing these pages once they resolve to a 500 error page?

**Comment by rschwab** [comment]
@JessWaggs That's correct!

**Comment by rmjaffe** [comment]
Working as expected in production.
