### ISSUE TITLE
(3) NoMethodError: undefined method `casecmp'

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#405]
This error came up while attempting a round trip on [this importer](https://digitalcollections.library.ucsc.edu/importers/6?locale=en). I created an export based on this importer, edited the file to only include one work, and then updated the importer to use the new file. On the prod server this file is under /srv/hyrax/tmp/imports/6_20220728203859_47

Screenshot from sidekiq:
![Firefox_Screenshot_2022-07-28T21-21-37 686Z](https://user-images.githubusercontent.com/515412/181640185-8f273b73-76ea-499f-931c-a18cb6b02131.png)

**Comment by rmjaffe** [comment]
We're hanging on to this ticket for now to see if this error pops up again when ingesting.

**Comment by snehagunduraoUL** [comment]
This issue still exists when roundtripping. Needs further investigation. Increasing the points.

**Comment by snehagunduraoUL** [comment]
One more import-export that worked same as above.

input csv - [rstest220728.csv](https://github.com/UCSCLibrary/ucsc-library-digital-collections/files/10680467/rstest220728.csv)

Roundtrip csv : [export_385_from_importer.csv](https://github.com/UCSCLibrary/ucsc-library-digital-collections/files/10680471/export_385_from_importer.csv)

**Comment by snehagunduraoUL** [comment]
Moving this back to Bugs as it resurfaced during aerials ingest roundtripping on sandbox

**Comment by snehagunduraoUL** [comment]
Update : Csv had an empty row with just parent column which was causing the casecmp bug.
