### ISSUE TITLE
Course Pages: 2. Expose track list by default and make styling changes

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#41]
Expose track list by default and make styling changes (see img in UI report):

- Unselected bg color: #ddd
- Selected bg color: ##FECB45
- Font color: #000
- Add 1px #7A7A7A border around track list

See [Course Pages, 2](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit#bookmark=id.v2bzq6nvpf4c).

**Comment by NedHenry** [comment]
There is now an error displaying the track list at all, which I am addressing shortly. I will make these styling changes at the same time.

**Comment by NedHenry** [comment]
display bug fixed in 2648988bea2dc30bcd17abcdd010d9a2d4a122bb, styling changes made in 4e1b0c31e3cda8b8f7cca576447466380f536369
