### ISSUE TITLE
(2) Fix CSV permission issue on production

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/ucsc-library-digital-collections#414]
Sidekiq shows a permission issue for the import csv.

**Comment by rschwab** [comment]
Still seeing this on sandbox.

Importer: http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/210?locale=en

Error in sidekiq:  Errno::EACCES: Permission denied @ rb_sysopen - tmp/imports/210_20220810162713/qasheet810.csv

**Comment by rschwab** [comment]
Saw the same error on production, this time using the "Create" button.

Permissions on the server:
[ryans@digitalcollections ~]$ ll /dams_derivatives/tmp/production/imports/
drwxrwxr-x. 2 sufia sufia 3 Jul 27 09:30 2_20220727163004
[ryans@digitalcollections ~]$ ll /dams_derivatives/tmp/production/imports/2_20220727163004/
---xrwx--t. 1 sufia sufia 8020 Jul 27 09:30 qasheetfail.csv

The file I uploaded looks like this on my machine:
-rw-rw-r-- 1 ryan ryan 8020 Jul 27 09:29 qasheetfail.csv

**Comment by rschwab** [comment]
Probably same issue as #403 for the 'create and validate' button. Closing that ticket as a duplicate.
