### ISSUE TITLE
(3) Make the thumbnail size uniform in the A-Z list

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/ucsc-library-digital-collections#420]
The thumbnails for collections are of different sizes in the A-Z list.

**Comment by snehagunduraoUL** [comment]
A couple of collections still have different thumbnail sizes.


![Image](https://user-images.githubusercontent.com/92340457/194113351-f6a85aae-9a62-4e28-8c6b-3c99b3dc07d8.png)

**Comment by rschwab** [comment]
It looks like the code is missing in sandbox currently. Compare:
https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/473/commits/a0b681dd7ff5e77b1dc81ecfe35b017c7cf0c012
with
https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/86c3e5447d87f9a2633e8ce4dddf3c4ec3276251/app/assets/stylesheets/ucsc.scss.erb#L858

**Comment by JessWaggs** [comment]
The thumbnails are all the same size! 

However, the spacing between the thumbnails is not uniform (is that a different ticket?)

**Comment by rmjaffe** [comment]
Not sure is this observation belongs here or on #382, but just noticed that there's a blank space in the A-Z list of collections:

![Image](https://user-images.githubusercontent.com/32003407/207135852-a8115b3f-6c62-46bc-a5bf-33c6b4316fc9.png)

Not sure why this is but I'm seeing it in both Firefox and Safari.  I am not logged into the DAMS.

**Comment by rschwab** [comment]
I think this should be a new ticket, because we'd need to discuss the options. The root cause is that some collections have a longer height because of having a longer title that goes onto two lines.
