### ISSUE TITLE
(11) Local authority links should display in all environments

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#421]
# Summary

Currently local authority terms don't appear in sandbox. The suspected cause is a potential hard-coded URL to production for local authorities. This should be fixed to display local authorities in all environments.

### Links to Examples 
- [Bulkrax Entry](http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/121/entries/1004?locale=en) 
- [Work](http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/121/entries/1004?locale=en) 
  - Note how Creator does not render 
- [Work edit form](http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/121/entries/1004?locale=en) 
  - Note the error in the Creator input(s) -- `Unable to fetch label for http://digitalcollections-staging-sandbox.library.ucsc.edu/authorities/show/local/agents/djskagalsdjfg` 
- [Endpoint](http://digitalcollections-staging-sandbox.library.ucsc.edu/authorities/show/local/agents/djskagalsdjfg) for local authority 

# Steps to Reproduce

1. Download this CSV: [local_auth.csv](https://github.com/UCSCLibrary/dams_project_mgmt/files/8663860/local_auth.csv)
2. Login as an admin user 
3. Navigate to Dashboard > Importers > New 
4. Fill out required fields. Upload the CSV from step 1 
5. Click "Create and Import" 
6. Navigate to the imported Work's public show page. Note that no Creator values render 
7. Navigate to the imported Work's edit form. Note the error in the Creator input(s) 

# Notes 

- The code for minting local authorities lives in the [ControlledIndexerBehavior](https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/sandbox/app/indexers/controlled_indexer_behavior.rb#L150-L164)

**Comment by rmjaffe** [comment]
In ingesting a small test collection, Bits pix, I've noticed the following regarding the controlled terms:

- Geonames URIs are correctly displaying as labels in the public facing metadata records
- All Getty URIs are displaying as URIs (http: and https:)
- Some LCSH are displaying URIs and some are displaying as labels

Of the LC URIs, the https: URIs display properly as labels whereas the http: URIs do not.  For example, in looking at the test object [EvilDonut.jpg](http://digitalcollections-staging-sandbox.library.ucsc.edu/records/b2773v944), three subject terms should be present in the metadata record two of which are LCSH:

https://id.loc.gov/authorities/subjects/sh85021262 displays Cats
http://id.loc.gov/authorities/subjects/sh90001071 displays http://id.loc.gov/authorities/subjects/sh90001071

I didn't observe any issues with the ingest or display of any local controlled terms (i.e. text strings) I included.  I did not include on my test spreadsheet any local terms that have previously been ingested into sandbox.

**Comment by rmjaffe** [comment]
@snehagunduraoUL Just successfully ingested a [test collection of two images]([authorities_test_RJ_2](http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/257?locale=en)) and it looks like the Getty and LC authorities are working correctly!  I was looking specifically to see if the following URIs would match and display the appropriate labels:

http://vocab.getty.edu
https://vocab.getty.edu
info:lc/authorities
http://id.loc.gov/authorities
https://id.loc.gov/authorities

The only issue I noticed is that none of the values I had entered into subjectTopic display in the metadata records for either of the [objects](http://digitalcollections-staging-sandbox.library.ucsc.edu/catalog?locale=en&q=Production+files&search_field=series).  Not sure why that is.

**Comment by rschwab** [comment]
I think this was resolved in [PR 499](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/499)
