### ISSUE TITLE
(2) Conduct MVP needs assessment: define tasks

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#423]
### Descriptive Summary

The DAMS team and stakeholders are wanting to do a revised DAMS needs assessment to determine what functionality is required for the DAMS to reach the standard of being a minimum viable product (MVP).  Part of the work of this assessment is to determine what an MVP DAMS looks like and make recommendations as to what development is required to get us to that point.  It is also an opportunity to reset expectations around the DAMS project in terms of development speed, identifying and balancing priorities, and the type of content and user experiences we can accommodate.

### Deliverables

- [ ] Organize work in to task tickets

**Comment by afrebert** [comment]
@JessWaggs will review and modify ticket. Thanks, Jess!

**Comment by rmjaffe** [comment]
@JessWaggs How many points should we put on this?  3?
