### ISSUE TITLE
(13) Increase support and efficiencies for ingest of high-volume collections

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#426]
### Descriptive Summary

At present ingests larger than 1K objects are failing.  We want to investigate what is causing this and come up with a plan for accelerating these ingests.  Some of our digital collections number over 10K objects; at present we can employ a workaround of cutting up the ingest spreadsheets into smaller ingests, this solution is not sustainable over the long term.

### Acceptance Criteria

- [ ] Investigate this issue and have relevant conversations; report back to team
- [ ] Propose possible solution(s)
- [ ] Test a large ingest (based on back-end MVP needs) and monitor CPU/RAM/Disc usage to identify bottlenecks

**Comment by rmjaffe** [comment]
Link to Tania's note from meetings with Sue and ITS re: ingest issues: https://docs.google.com/document/d/1Bt0eKbPoS97HaT42uXWAcTUqzgNPyx__p-SA9pe3SWI/edit?usp=sharing

**Comment by snehagunduraoUL** [comment]
Looks like multiple copies of images are not being created (rather getting created and deleted by hyrax) now after the kakadu issue has been fixed. Those copies of images were retained by hyrax because the derivatives were not created by kakadu.

**Comment by snehagunduraoUL** [comment]
Update : Uploaded part of Aerial photos on sandbox. One of the imports made was upt o 1235 records which took ~40 mins.
