### ISSUE TITLE
(5) Assess options for tier one complex image objects display

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#438]
### Descriptive Summary

We have two proposed interim solutions we could implement:

- #395 
- #412 

We're interested in getting a sense of the development work and amount of effort that would be required of each option, as well as a sense of which option would better set us up for eventually implementing our tier two approach, #396 & #397.

### Acceptance Criteria

- [ ] Statement of estimated effort
- [ ] Recommendation is support of #395 or #412

**Comment by rschwab** [comment]
Trying to capture what we decided in the meeting earlier. @rmjaffe @JessWaggs @snehagunduraoUL feel free to edit this if I've missed anything.

1. Parent objects will have their representative image directly attached to the work, in other words a copy of the file will go into the filenames column of an import spreadsheet for a parent object.
2. Thus parent metadata will display with the representative image on the parent object page.
3. The child object whose image has been used will also have the same file attached via the filenames column, and will appear in the list of children on the parent object.
4. Thus child metadata for the representative image can be seen by clicking on the child object in the list of children on the parent.
5. In cases where a representative image is desired for search result pages, but not on the parent object page itself, front-end conditional code will be used to hide the image on the parent object page (most likely on a per-collection basis).
6. If we ever have a case where we don't want a representative image for search results or the parent object page, the filename for that parent object can just be left blank.

**Comment by rmjaffe** [comment]
Thanks, @rschwab you beat me to this and summarized it better than I would have.

**Comment by JessWaggs** [comment]
@rschwab Looks good to me. Thanks Ryan!
