### ISSUE TITLE
Course Pages: 5. Spell out value in Language element rather than use abbreviated form (eg. eng -> English)

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#44]

**Comment by NedHenry** [comment]
This is addressed by c710ab99444fc56f5be0c954bc6ff910f1903941, not yet deployed in production.
Unfortunately, the display of languages in courses and lectures is currently not working correctly due to a separate indexing problem (issue #55). 
Soon, languages will be a controlled vocabulary.

**Comment by NedHenry** [comment]
now deployed
