### ISSUE TITLE
(3) Implement ADD functionality for Collection-->Works

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#452]
### Descriptive summary
ADD functionality has been added to the inheritance rules for Works-->Works (#346), but has not yet been implemented for Collections-->Works.  We would like for works to inherit values from selected properties within the collection-level metadata record (i.e. the same Work-->Work) and for those collection-level values to be added to whichever values are already present within the selected properties within the works records.

### Acceptance criteria
**Done means:**
- [ ] ADD rules introduced and work Collection-->Works
- [ ] Update bulkrax documentation to note that inheritance doesn't work for collections/works added to existing collections/works

### Related work
#346

**Comment by rmjaffe** [comment]
@snehagunduraoUL Just added a criterion for updating the bulkrax doc and added a point.

**Comment by rmjaffe** [comment]
@snehagunduraoUL Should this have 34 points on it or did we goof up?

**Comment by snehagunduraoUL** [comment]
That has to be just 3 :)

**Comment by rmjaffe** [comment]
Will QA with when reviewing the first ingest of aerials into production.

**Comment by rmjaffe** [comment]
Had planned to QA this with the aerials ingest, but we've decided to turn off the inheritance rules for subjectPlace which would have been the only property using the ADD rule in this collection.  As it was working correctly in sandbox and as we've decided to turn off inheritance entirely, closing this ticket out.
