### ISSUE TITLE
Course Pages: 11. Add a “Permanent Link” that prints the object’s URL

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#46]
See image in [Course Pages, 11](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit#bookmark=id.v2bzq6nvpf4c).

**Comment by NedHenry** [comment]
Permalink structured was defined for the OAI-PMH feed in 25a12c6b34394199e0198f82bd57573f803361c1, and was added to item show pages in 1d3ba524fe8eb9c9794de0a5ed677d685413b2de, which has not yet been deployed in production

**Comment by NedHenry** [comment]
deployed
