### ISSUE TITLE
Search Results: 1. Elements to display

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#47]
Only display the following item elements on the search results screen:

1. Title
2. Description
3. Keyword
4. Subject
5. Creator
6. Creator
7. Date Created
8. Resource Type

**Comment by NedHenry** [comment]
This was addressed in: 8f79e855a224ea4044983bec6530233d2071a2ae
Fixing this exposed a bug in how ScoobySnacks was configuring Blacklight. 

In ScoobySnacks, the bug was fixed in this commit b5234104fdfa3e6a6054e48450bd350d18a36f8c
(apologies for the confusing commit msg)
