### ISSUE TITLE
(5) Update/develop & test checklists for production QA of new ingests

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#472]
### Descriptive summary
Earlier in the DAMS project, Sue was doing most of our production QA for ingests as well as front-end features and enhancements.  Working with Sue, the DAMS team wants to review, update existing QA documentation and develop checklists to guide QA work so that it might be completed by both non-developer DAMS team members or others in the library (staff, students).

At present, we have the [New Ingest QA Template](https://docs.google.com/spreadsheets/d/1VRffZmmXkURvLYbvKB9wy26UUDUnD2ySwNPW5E2MzMQ/edit#gid=0) Sue created, but do not have a similar tool to use for evaluating features/enhancements.

### Background

In the 9/22 Digital Project meeting, AF, SCP, TM and RJ determined that this work was needed and that @afrebert and  @rmjaffe would work on this with @chesleyperry.

### Acceptance criteria
**Done means:**
- [x] (Re)develop checklist of QA steps for post-ingest collections
- [x] Use QA template to QA Grateful Dead Media Collection in production (staff/student non-expert use case)
- [x] Use QA template to QA a test set in sandbox (initial ingest, DAMS member use case)
- [ ] Document QA procedures, add to Wiki
### Related work
#477

**Comment by rmjaffe** [comment]
@chesleyperry created an[ ingest QA checklist](https://docs.google.com/document/d/1FYodUFmTdy-2Qf-num9ZkmbbNuF2ueh9OYuxCzehdIA/edit#) based on the previous spreadsheet; @rmjaffe and @afrebert will QA the QA checklist by using it to QA a test collection in sandbox.

I recently ingested a test set of three work as an Bulkrax importer called [inheritance_test_RJ](http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/227?locale=en).  This [test set of kitty pics ](http://digitalcollections-staging-sandbox.library.ucsc.edu/collections/6w924b95h?locale=en)could be used for QAing the QA checklist as there's a lot of issues.  The ingest spreadsheet and files are on dams_ingest in the Inheritance_Sample_RJ folder.

**Comment by afrebert** [comment]
As @rmjaffe suggested, I will do a trial run of the ingest QA list using [Grateful Dead Media collection](https://digitalcollections.library.ucsc.edu/collections/8k71nh08w?locale=en), adding issues to the already existing clean up ticket (https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/380)

**Comment by rmjaffe** [comment]
@afrebert I haven't yet had a chance to use Sue's checklist with the test ingest in sandbox, but hope to get to this this week.  Also, I rescoped this ticket so that it covers the QA checklist for ingests only.  Created #477 for developing a checklist for new features which I'll put in Ready for Development.  How many points should be put on this card?

**Comment by rmjaffe** [comment]
@afrebert @chesleyperry Just finished using the checklist to QA a small test ingest I loaded in the sandbox: https://docs.google.com/document/d/1aryncwHyPvXOijL7aK6EmVZ2-pffTYF0ixUl9To-eZQ/edit?usp=sharing

In the guise of expert user/DAMS team member performing an initial QA of a collection, I found the form to be super easy to use, hit all the marks and served very well in conducting a high-level review.  In considering the second use case, students and non-expert staff doing QA, I agree with Angelika probably best to push this into a spreadsheet so that the collection can be evaluated on item-by-item vs. overview basis.  Perhaps have this be a two-tab spreadsheet:  first tab collection-level QA, second tab item-level QA?

At this point, would it serve for the three of us to meet and chat about our findings and next steps?

**Comment by rmjaffe** [comment]
We've determined that the [checklist](https://docs.google.com/document/d/1FYodUFmTdy-2Qf-num9ZkmbbNuF2ueh9OYuxCzehdIA/edit#heading=h.tns7uex6u0r0) meets our present needs; if we run into a mass of issues when QAing the aerials ingest that are best documented item-by-item, we can revisit the idea of developing a QA spreadsheet then.
