### ISSUE TITLE
Lectures Pages: 1. Hide page elements

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#48]
Hide: 
- “Open Access” tag/annotation
- “Last modified” date
- format thumbnail

See examples in [Lecture Pages, 1](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit#bookmark=id.e0v1exb11v84).

**Comment by NedHenry** [comment]
Should these changes apply to course pages (and other work pages) as well as lectures?

**Comment by NedHenry** [comment]
I think I remember you saying that the general notes on show pages should apply to all work types. I have been applying these notes under that assumption.

**Comment by NedHenry** [comment]
Addressed in 1d3ba524fe8eb9c9794de0a5ed677d685413b2de and 1d3ba524fe8eb9c9794de0a5ed677d685413b2de and 3342102b6dfa137e9876f104f836e6b3e6a4491c, not yet deployed in production

**Comment by NedHenry** [comment]
deployed
