### ISSUE TITLE
(3) Create mockup for faceting on A-Z page

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#488]
### Descriptive summary
A ticket exists for enabling faceting on the A-Z all collections page, but we don't know how the page should look with that functionality added on.

### Acceptance criteria
**Done means:**
- [x] Mockup created and shared
- [x] Create implementation ticket

### Related work
#376

**Comment by JessWaggs** [comment]
@rmjaffe @rschwab Could I get some preliminary feedback on these designs? I tried using facets with the current two column layout, but I couldn't achieve something I found usable.

Thanks!



[AtoZ_Page_rev2_facets.pdf](https://github.com/UCSCLibrary/ucsc-library-digital-collections/files/9923276/AtoZ_Page_rev2_facets.pdf)

**Comment by rmjaffe** [comment]
@JessWaggs I really like this.  It looks really clean and I especially like the inclusion of the collection descriptions and extent.  One question:  On the mockup four facets are shown whereas on the collection landing pages we have seven available facets. Are we wanting to duplicate what's on those landing pages?  Or do we want to limit to four on the A-Z?  If so, which facets do you recommend including?

**Comment by JessWaggs** [comment]
@rmjaffe Oh, I hadn't even considered _which_ facets. I'm not sure I'm familiar enough with the collection level metadata to give a recommendation around that. What are your thoughts on collection level faceting?

**Comment by rmjaffe** [comment]
If we're to limit to four -- I'd go with subjectTopic, subjectPlace, subjectName, and creator?  Or possibly physicalFormat in place of creator (note:  physicalDescription does not appear as a facet option among the seven on the collection landing pages)?  That said, any decisions we make right now are interim decisions.  There are a number of facet-related tickets in our Planning queue addressing which facets, how to rework facets, and how to order facets, facets, facets, and more facets.

**Comment by rmjaffe** [comment]
Also note, at present, there aren't subject values in the collection level metadata, but there's a ticket for adding them: [Add subject terms to collection-level metadata records#378](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/378)

**Comment by JessWaggs** [comment]
I think we can go beyond 4, I just stopped there in the mock up for efficiency : )

Since this is an interim decision, maybe we should just include all facets that would work for collection faceting currently. Sounds like we can revisit that when we move on to the facet-specific tickets?

**Comment by rmjaffe** [comment]
I can pull #378 into the next sprint so that we can include the subjectPlace, Name and Topic as facets as well as creator/contributor.  Would we want to include donor?

**Comment by JessWaggs** [comment]
Donor doesn't seem like it would used by very many end users (particularly students). But if it's useful for SC&A staff, I see no problem including it

**Comment by rschwab** [comment]
Thanks Jess! I agree this looks good so far. Questions/comments:
- The facet panels are styled differently than currently in the app. Is this intentional - or do we want them all the same? If the same, should we make a new ticket to change the facet styles to match this mockup, or should this mockup be considered to use the existing styling?
- Should I limit the per page to 5, or leave it at the current 24, or some third option?
- The search within the collection bar isn't on the mobile mockup, was that intentional?

**Comment by JessWaggs** [comment]
Hi Ryan!

- I think the facets in my designs are ahead of the DAMS. I did question whether to use the facets from my other mock-ups or the current ones. I think the answer is to style them according to the current site styles but in a future ticket, I think facet styling is going to come up.
- 24 will probably be too long when we move to one column... how about 10?
- Oh good point! I totally spaced on that for mobile. I'll put it in for the final draft!
