### ISSUE TITLE
Lecture Pages: 2. Modify Breadcrumbs

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#49]
Preferred Option: 
- Remove “My Dashboard / Your Collections” from breadcrumbs and replace with Course / Collection  (see image below)
- Alternative option: Remove breadcrumbs entirely

See image in [Lecture Pages, 2](https://docs.google.com/document/d/1d2OqM0FfaHSH_GsRJe1ymy0aa99W8Pv2mlUEW9pPhtk/edit#bookmark=id.e0v1exb11v84).

**Comment by NedHenry** [comment]
Addressed in 13a07c78a6b937e3ef8f7ef204dbc324e849b13e (with issues), fixed in 96052918c41cdfd8cd69ebdb955c7b1ded2997fc and cba27465963ec63b4aa585de16239f198c72beb7. These are not yet deployed in production.

**Comment by NedHenry** [comment]
deployed
