### ISSUE TITLE
(5)Images not displaying on newly created works

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#504]
While trying to add the logo as the representative image for the GDAO media, I was unable to get the image to display. This happened with both png and tiff files, and using both the UI and Bulkrax.

**Comment by rschwab** [comment]
Discovered the ssl certificate for 2022 had never been applied to the cantaloupe.properties file for either production or sandbox instances. I created a p12 file using the key and certificate, and updated both cantaloupe.properties files and restarted the services. Images are still not working, however. Here is the error message in sidekiq:
`RuntimeError: Unable to execute command "kdu_compress -quiet -i /srv/ucsc_sufia_sandbox/releases/20221216212229/sufia20221219-555-k874e.tif -o /srv/ucsc_sufia_sandbox/releases/20221216212229/sufia20221...`

**Comment by rschwab** [comment]
[This comment](https://github.com/UCSCLibrary/dams_project_mgmt/issues/538#issuecomment-1146397963) looks relevant. Apparently reverting [this pull request](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/305/commits/a81ee5fe4b26885641566472ca4d2688e8517640) fixed the issue back in June.

**Comment by rschwab** [comment]
It's possible that Kakadu version 7 no longer works? There is a new version 8.3 that we can install, Ticket #532 covers that upgrade.

**Comment by rschwab** [comment]
Tried adding /usr/share/kakadu to the global path using a new kakadu.sh in /etc/profile.d. This worked to get the path variable updated, but the errors are still showing in sidekiq.

**Comment by rschwab** [comment]
Trying the same tactic but for libraries using:
`[root@digitalcollections-staging-sandbox ~]# echo '/usr/share/kakadu' > /etc/ld.so.conf.d/kakadu.conf
[root@digitalcollections-staging-sandbox ~]# ldconfig -v`

**Comment by rschwab** [comment]
This fixed it! Repeating these commands on staging and production next:

> echo '/usr/share/kakadu' > /etc/ld.so.conf.d/kakadu.conf
> ldconfig -v
> echo 'pathmunge /usr/share/kakadu' > /etc/profile.d/kakadu.sh
> chmod +x /etc/profile.d/kakadu.sh 
> . /etc/profile

**Comment by rmjaffe** [comment]
GDAO logo displays!  Deadheads and archivists will be pleased.
