### ISSUE TITLE
(3) Break up aerials spreadsheets and files into 1,000 item chunks

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#508]
### Descriptive summary
Break up aerials spreadsheet and files into 1,000 item chunks so that we don't run into any issues with ingesting the collection.  Spreadsheets and files are both currently on dams_ingest.

### Acceptance criteria
**Done means:**
- [x] Spreadsheets are split into sheets of roughly 1,000 files
- [x] Files are split into folders that correspond to the items represented on each of the spreadsheets

### Related work
#418

**Comment by rmjaffe** [comment]
I have the same situation with on of the larger flights that is almost 2K images.  If I split it onto two ingest spreadsheets, can I include the same parent work record on each so that values will inherit onto the child works?

**Comment by snehagunduraoUL** [comment]
@rmjaffe let's include the collection level metadata on each of the spreadsheets for bulkrax to roundtrip everytime. Same would apply for the parent work.

**Comment by rmjaffe** [comment]
@afrebert All yours :) Aerials spreadsheets have been split into 21 files.  Please note that a couple of the flights, 1956-C and 1966-D have been split onto two spreadsheets.

All spreadsheets are here: smb://dams.library.ucsc.edu/dams_ingest/Aerials Spreadsheets.  Ignore what's in the 'Older' folder.

**Comment by afrebert** [comment]
@rmjaffe I've been moving file sets into folders that reflect the new spreadsheets. I'm up to Aerials_10_1956C_1 and _2 where I noticed that spreadsheet 1956C_**1** starts with indexes, then lists 1956c_abg_**10r**-010.tif through 1956c_abg_**19r**-204.tif whereas on 1956C_**2** we have the lower numbers

**Comment by rmjaffe** [comment]
I double checked the order against earlier versions of the spreadsheet including the one Sue last checked and the order is unchanged from what you're seeing on the two current 1956-C spreadsheets:  Index rows, 10r-19r, and then 01r, 20r, 21r and so forth.  I've never updated or more given much thought to the order of the files on the spreadsheets.  I don't think it's an issue, but we may want to check with @chesleyperry.  If there's an authoritative order the sheets ought to be in, that's new to me.

**Comment by chesleyperry** [comment]
@rmjaffe - I don't think there's any need for a specific order of the files (images) for each flight -- except that it would be good for the indexes to display first when browsing all images in a flight.  As part of the file and metadata checking, we moved the indexes up to the top (under the collection-level metadata row) on the spreadsheets.

**Comment by rmjaffe** [comment]
@chesleyperry Thanks, Sue.  I didn't think it mattered either.  All the 'new' index sheets are at the top of each flight; any legacy index maps we've chosen to include (in addition to the new index maps) are at the end of flight.
