### ISSUE TITLE
(1) Typo in metadata.yml

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#523]
For the description field it is marked as `full_text_searachable: true` but should be `full_text_searchable: true`

**Comment by rschwab** [comment]
Typo corrected in the pull request above, but this change would require a SOLR re-index for the change to take effect.

**Comment by snehagunduraoUL** [comment]
@rschwab was this typo causing any issue?

**Comment by rschwab** [comment]
Strangely enough, it appears no. I was able to search "themes centered around women" and it brought up the works with that sentence in the description.

**Comment by snehagunduraoUL** [comment]
Okay..I'll move it to staging then.

**Comment by rschwab** [comment]
fixed in production.
