### ISSUE TITLE
(1) A-Z page: blank spaces in list

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#525]
### Describe the bug

There a gaps in a couple places on the current A-Z all collections page.  @rschwab noted that "the root cause is that some collections have a longer height because of having a longer title that goes onto two lines" in the comments on #420.

### To reproduce
**Steps to reproduce the behavior:**
1. Go to ['...'](https://digitalcollections.library.ucsc.edu/collections)
2. Scroll down to the list and you will see the gaps in couple places on the list.

### Expected behavior
There should not be gaps in the list.

### Screenshots
Example 1:
<img width="1271" alt="Screen Shot 2022-12-12 at 11 21 26 AM" src="https://user-images.githubusercontent.com/32003407/207148733-29599daa-d965-429b-8e23-945550f29e67.png">

Example 2:
![Screen Shot 2022-12-12 at 12 34 45 PM](https://user-images.githubusercontent.com/32003407/207148836-56123a8d-f467-4f73-a2e6-1ef57db1a79b.png)

### Desktop (please complete the following information):
 - OS: Mac
 - Browser: Firefox, Safari

### Acceptance criteria
**Done means:**
- [ ] There are no gaps in the list

**Comment by rschwab** [comment]
I've uploaded screenshots for two ways of resolving this to a [folder in our DAMS drive](https://drive.google.com/drive/folders/14PoC0g6aOwltj81bmq97vOI2NVxsiHEO?usp=share_link). There's also a third more code-involved option, detailed below.

1. Use flex-box layout
This method is probably the cleanest way to address the issue using CSS. Flex-box deals with rows and columns more cleanly that the float method used by default in our theme. The potential drawback is that when two item in a row have very different description/title lengths, there's lots of space added around the shorter one.

2. Manually setting a height on each collection
This method is the most direct way to address the issue and gives us the most control on the layout. The drawback here is that it might clip items with very long descriptions or titles. And we'd need to scale the height with the browser width - see the tablet version currently broken in my screenshots. This can be addressed, but ultimately this method is the most fragile.

3. Set a max length on titles and descriptions that ensures a uniform height
In the same way we are currently limiting the length of the description, we could more aggressively limit the length of the title so its always one line, and the description so its always 3 lines. This fixes the issues without changing anything about our current layout, but it would mean titles would get cut off with ellipses.

@JessWaggs and @rmjaffe what do you think? My preference is for option 1.

**Comment by rmjaffe** [comment]
@rschwab Thank you for laying out and explaining all the options.  I defer to your judgment, but I agree option 1 seems best.

**Comment by JessWaggs** [comment]
@rschwab I think Option 1 is the best approach as well. Just wanted to note that we will be moving away from the two column approach for the A-Z page once we implement faceting. So it also seems like a quick-fix solution would be fine here.

**Comment by JessWaggs** [comment]
@rschwab Sandbox looks good to me - I don't see any blank spaces!

**Comment by JessWaggs** [comment]
@rschwab Looks good in prod too!
