### ISSUE TITLE
(5) MVP Assessment for admin user functionality

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#528]
### Descriptive summary
DAMS team has determined that we need to do an MVP assessment of our admin user functionality, i.e.: what is needed to support non-developer ingest/export/bulk editing of metadata and files, and/or editing individual work or collection metadata records using the UI, etc.

### Background
Revisit DAMS priorities for N8: https://docs.google.com/document/d/1e-Y__kE7x4NlGKItezLIS1dX-N25lyMmGbQlx27-1pc/edit#heading=h.40ermu27wlwl

### Acceptance criteria
**Done means:**
- [x] Identify & schedule stakeholders/participants for focus groups
- [x] Develop questions for focus groups
- [x] Conduct focus group/interviews with DAMS admin users
- [x] Identify key needs and recommendations

### Related work
#494 
#520

**Comment by JessWaggs** [comment]
@rmjaffe @chesleyperry @afrebert Please take a look at my [MVP for Admin User Needs](https://docs.google.com/document/d/1rvVyluoeLdK-PCS53Q8ogEbU5SHswPxcqPd_JG8817A/edit#heading=h.agvh27bspypw) draft and let me know if I missed anything or other feedback/suggestions. Thanks!
