### ISSUE TITLE
Upgrade Kakadu to v8

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#532]
Found an email from Kerry with a link to download Kakadu 8.3. We are currently using 7.10. We should install the new version.

I've added the [downloaded zip file](https://drive.google.com/file/d/1lmG_M9lQoSJDUrPJvHk6DRzwrsLiCz_j/view?usp=share_link) to our shared Drive. We need to compile it, install it onto each machine, then we should remove this zip from drive.

- [ ] Compile kakadu 8.3
- [ ] Install on sandbox
- [ ] Install on staging
- [ ] Install on production
- [ ] Clean up file from G Drive

**Comment by rmjaffe** [comment]
@rschwab Looks like we've got two cards for this Kakadu upgrade. #377 is the other.  Any preference on which to keep?

**Comment by rschwab** [comment]
@rmjaffe I combined them into the ticket you created. I did remove the email message with sensitive info and put the link to the file on Google Drive. Closing this one as a duplicate.
