### ISSUE TITLE
(3)Inheritance: NoMethodError - undefined method `id'

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#538]
When ingesting works that would inherit a controlled value, the following error shows up:
`NoMethodError - undefined method 'id' for "https://id.loc.gov/authorities/names/n82217191.html":String`

This is traced to line 145 of app/models/work.rb, which tries to select the id from a controlled vocabulary term. In this case the import used a string URI to ingest the term. In another instance where this bug came up was a round trip on a value with the legacy BulkOps `<#activetriples>` format of controlled vocabulary term.

**Comment by rschwab** [comment]
Even updating a parent object with a blank for the term (to try and remove it) causes this error:
`Error: NoMethodError - undefined method 'id' for "":String`

Basically anything that inherits a controlled vocab term will cause this error.

**Comment by snehagunduraoUL** [comment]
@rschwab  could you please add the steps to recreate this issue?

**Comment by rschwab** [comment]
I tried to re-create the bug with [this importer](http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/329?locale=en), but now the error is not popping up. However, the subjectName didn't inherit from the collection to the work. Here's the spreadsheet:


[bug-538-test.csv](https://github.com/UCSCLibrary/ucsc-library-digital-collections/files/10395990/bug-538-test.csv)

**Comment by snehagunduraoUL** [comment]
Okay. I see the issue now. Getting the undefined method 'id' for "":String error now. Will work on it.

**Comment by rschwab** [comment]
I don't see this error any longer either.

**Comment by snehagunduraoUL** [comment]
Works as expected in production. No error.
