### ISSUE TITLE
(5)Duplicate results for controlled fields with inheritance

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/ucsc-library-digital-collections#544]
Duplicate controlled field values are displayed with work->work and collection->work inheritance. Here is an example on sandbox.
http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/m326m177s?locale=en

**Comment by snehagunduraoUL** [comment]
Solr saving duplicate values. Here is the solr_doc when printed in the logs. 


![Image](https://user-images.githubusercontent.com/92340457/212218576-7f747c1b-5b7c-4c97-8dd5-6c18b407ad78.png)

**Comment by rmjaffe** [comment]
@snehagunduraoUL I just ingested a test set (a collection containing two works on of which has two child work): [Inheritance_dupes_check_RJ](http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/349?locale=en) and am getting weird results in terms of what values are inheriting (or even showing up on the show pages) from the collection onto the works, and it doesn't seem that values are inheriting from the parent to the child works at all.  Want to have a look?

But I'm not seeing any duplication ...

**Comment by snehagunduraoUL** [comment]
Sure. Let me take a look. Can you share the csv please?

**Comment by rmjaffe** [comment]
@snehagunduraoUL It's here: smb://dams.library.ucsc.edu/dams_ingest/TESTS/test_ingest_flowers_20221021/Test_flowers_3_20230118.csv

**Comment by snehagunduraoUL** [comment]
@rmjaffe I tried the above csv by changing a couple of things..and the inheritance worked.

- changed the bulkrax identifiers
- date format to mm-dd-yyyy
- url "info:lc/authorities/sh85039336" to "info:lc/authorities/subjects/sh85039336" 
Here is the import http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/360?locale=en

**Comment by snehagunduraoUL** [comment]
[Test_flowers_3_20230118.csv](https://github.com/UCSCLibrary/ucsc-library-digital-collections/files/10486716/Test_flowers_3_20230118.csv)

**Comment by rmjaffe** [comment]
Thanks, Sneha!  The test items look good to me.

**Comment by snehagunduraoUL** [comment]
@rmjaffe Is it okay to move this change to staging?

**Comment by rmjaffe** [comment]
I think so :)

**Comment by snehagunduraoUL** [comment]
works as expected on production.
