### ISSUE TITLE
(5)MVP assessment & recommendations: upgrading DAMS stack

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#552]
### Descriptive summary
DAMS team has determined that we need to do an MVP assessment of the DAMS stack: What versions of software are we on?  What are the latest versions?  What is the most stable versions?

And to make recommendations and to estimate the amount of effort/time needed to upgrade pieces of the stack.

### Acceptance criteria
**Done means:**
- [x] Produce a report listing the component pieces of the DAMS, their current version, the latest version of the software, and recommended version
- [x] Estimation of effort, time, and potential impacts involved in upgrading the system.
- [x] Generate tickets for upgrades

**Comment by snehagunduraoUL** [comment]
https://docs.google.com/document/d/1d5TedJzFLl97xv7IwewVVa1SKS60gwQhLa3-HCuLIhc/edit#
