### ISSUE TITLE
(2)Controlled vocab term shows as 'false'

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#554]
On sandbox only as of 1/26/2023:
Importing a work with a controlled vocabulary term, in this case a subjectName value of `http://id.loc.gov/authorities/names/n82217191` displays on the work edit form as "false", and doesn't display on the front end at all.

[Work show page](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/vq27zn784?locale=en)
[Work edit page](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/vq27zn784/edit?locale=en)

The value exports exactly as imported ([see the export here](http://digitalcollections-staging-sandbox.library.ucsc.edu/exporters/21/download?locale=en)).

**Comment by rschwab** [comment]
Works perfectly now. TY!

**Comment by snehagunduraoUL** [comment]
No error on production.
