### ISSUE TITLE
(2) Mock Up for Interim Complex Object UI: Desktop

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#563]
### Descriptive summary
Currently, parent metadata is shown with the first child in a complex object. That child's metadata is not visible and it is not clear to the end user that the metadata they see is for the set of children.

We need an interim and quick to deploy UI solution to solve this problem.

### Acceptance criteria
**Done means:**
- [x] Mock up for interim UI in desktop
- [x] Create ticket for desktop development

### Related work
#395 
#564 
#438

**Comment by JessWaggs** [comment]
@rschwab @rmjaffe Please review mock up and provide any feedback. Thanks!


![Image](https://user-images.githubusercontent.com/6412857/218581489-974dce83-87aa-452f-a3a9-f53a53f43de2.png)

**Comment by rschwab** [comment]
Looks great to me. We may have to discuss what happens on a "download" of this work. Right now this grabs the "display_image_url" for the image and creates downloads based on that. Currently this means it will download the image attached to the work as the representative image: the one that shows on search results page but is hidden in this mockup. If we wanted that instead download the entire set, it would require further development work.

**Comment by rmjaffe** [comment]
@rschwab That's a really good point about the download button.  Would it make sense to hide the button on the parent work display page until we're able to create a download the full set option?

**Comment by JessWaggs** [comment]
@rschwab If hiding it on the parent work is possible, I would be in favor of that. I don't think a user would have clear expectations about what would happen, but might guess they would get the entire set. @rmjaffe Do you think that would be a common need / use case to get the entire set?

I would opt to hide it for now :)

**Comment by rmjaffe** [comment]
Let's hide it for now.  As far as downloading the full set, I can see patrons wanting to do that for the aerials especially if the DAMS is meant to be the single point of service for that collection.  That said, developing functionality in support of the aerials is not a priority.  If down the road we decide that we want to add that functionality, we can create a feature ticket.

**Comment by JessWaggs** [comment]
Just to summarize: We will be hiding the Download button on the parent record 

![Image](https://user-images.githubusercontent.com/6412857/220483787-e341690a-47c1-4f3d-9f86-5d0564215bab.png)

**Comment by JessWaggs** [comment]
#577 created to apply new styling
