### ISSUE TITLE
(2) Mock Up for Interim Complex Object UI: Mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#564]
### Descriptive summary
Currently, parent metadata is shown with the first child in a complex object. That child's metadata is not visible and it is not clear to the end user that the metadata they see is for the set of children.

We need an interim and quick to deploy UI solution to solve this problem.

### Acceptance criteria
**Done means:**
- [x] Mock up for interim UI in mobile
- [x] Create ticket for desktop mobile

### Related work
#395 
#563
#438

**Comment by JessWaggs** [comment]
@rmjaffe @rmjaffe Please review the mobile mock up and provide any feedback. Note on interaction: in this design, the parent metadata, About this collection box, and download and share buttons are collapsed and can be displayed by selecting "About this set" link. Thought behind this design: we want the child thumbnails to display above the mobile "fold" and the parent-level metadata is less useful and more acceptable to hide behind a click.

![Image](https://user-images.githubusercontent.com/6412857/218580942-38095d04-e47c-47e5-bcdf-aabbd06631e0.png)

**Comment by rmjaffe** [comment]
These are great, @JessWaggs!  Thank you so much for preparing the mockups.

**Comment by rschwab** [comment]
This also looks good to me. My one hesitation is that I don't think that as a user I would think to click "About this set" to find the download & share buttons. I wonder if those could fit in the display or if a clever label change could improve that?

**Comment by JessWaggs** [comment]
@rschwab I think that's a good point - let me try to fit in just the icons for those buttons. I feel like icon-only is a fair approach on mobile. I'll have a revision up for you to look at soon.
