### ISSUE TITLE
subjectPlace not being indexed/included in facets

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#565]
### Describe the bug
As part of Ryan's work on #378, it was found that subjectPlace is neither being indexed nor appearing as a facet despite it is set to be both in the metadata.yml file.

This issue was observed with subjectPlace values entered in collection-level metadata records.

### Expected behavior
subjectPlace values entered at the work or collection levels are indexed and appear to users as facet-able values within the subjectPlace facet.

### Acceptance criteria
**Done means:**
- [x] Values in subjectPlace at work and collection levels are indexed
- [x] Values in subjectPlace at work and collection levels appear as facets

### Related work
#378

**Comment by rschwab** [comment]
This seems to be resolved on my local dev, its possible its fixed with #571

**Comment by rschwab** [comment]
Should be tested alongside #550, which I believe resolves this issue.

**Comment by rmjaffe** [comment]
In production, subjectPlace facets shows up and seems to be working correctly.
