### ISSUE TITLE
(2)Aerials metadata: Backslashes appearing in front of semi-colons

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#567]
### Describe the bug
In reviewing the aerials metadata, I've noticed that where semi-colons appear within the text of a description they are proceeded by a \.  Before bulkrax, we had used semi-colons as delimiters and backslashes (\;) as needed to escape them out.  After we adopted | as our delimiter, I removed the backslashes from the ingest spreadsheets, nonetheless backslashes are still appearing.  Not clear on why this is happening.

### To reproduce
**Steps to reproduce the behavior:**
1. Go to a work within the aerials collection, for example: http://digitalcollections-staging-sandbox.library.ucsc.edu/records/2b88qc57q
2. Look at the contents of the description property
4. See the \;

### Expected behavior
No backslashes!

### Screenshots

**_Example 1_**
**What I'm seeing in sandbox:**
<img width="535" alt="Screen Shot 2023-02-07 at 3 12 19 PM" src="https://user-images.githubusercontent.com/32003407/217390409-1aed8dc1-33aa-4aaa-865b-bdd59c0f0b39.png">

**What's on the ingest spreadsheet:**
_title:_ 1937 Santa Cruz County and Monterey County Flight 13-ABG 5-88
_inherited description_ (parent work=[1937 Santa Cruz County and Monterey County Flight 13-ABG](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/z316q192n?locale=en)): Santa Cruz County and Monterey County Flight 13-ABG: Salinas River Valley, from the Monterey Bay to San Ardo; including Watsonville and the Pajaro Valley, Elkhorn Slough, Salinas, Chualar, Gonzales, Soledad, Greenfield, King City, San Lucas, and San Ardo.

_**Example 2**_
**What I'm seeing in sandbox:**
<img width="486" alt="Screen Shot 2023-02-07 at 3 12 36 PM" src="https://user-images.githubusercontent.com/32003407/217390463-88d44f02-aaa1-4763-8cd6-edf5ca9252fc.png">

**What's on the ingest spreadsheet:**
![Screen Shot 2023-02-07 at 3 31 26 PM](https://user-images.githubusercontent.com/32003407/217390733-7314abb6-09ef-4938-882f-2bdf35410794.png)

### Acceptance criteria
**Done means:**
- [ ] Backslashes are no longer being added in front of semi-colons

**Comment by snehagunduraoUL** [comment]
This is a user error. The excel sheet that I used was an old one I guess. It already had the '\' in it. Tested again with example2 above and here is the result.
http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/8910jv00x?locale=en

**Comment by rmjaffe** [comment]
Good to know -- thanks for investigating and testing!  I'll keep any eye out for this to see if it becomes an issue again.

**Comment by rmjaffe** [comment]
Given that it doesn't seem to be real issue, should we close this out and move it to done?

**Comment by snehagunduraoUL** [comment]
@rmjaffe Yes. Sounds good to me.
