### ISSUE TITLE
(5)Update Geonames labels for counties to local labels

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#568]
### Descriptive summary
In subjectPlace on this [parent metadata record](http://digitalcollections-staging-sandbox.library.ucsc.edu/records/vh53ww04s) ‘Santa Cruz’ appears twice but in referring back to the ingest spreadsheet the values supplied on that parent metadata row are:
http://www.geonames.org/5393068/santa-cruz-county.html
http://www.geonames.org/5347903/felton.html
http://www.geonames.org/11903391/pogonip.html
http://www.geonames.org/12122399/san-lorenzo-river-mouth.html
http://www.geonames.org/11983700/san-lorenzo-valley.html
http://www.geonames.org/5393052/santa-cruz.html
http://www.geonames.org/5404900/university-of-california-santa-cruz.html

There are no subjectPlace values entered at the collection-level.  The cause for the seeming duplication is that the label Geonames supplies for Santa Cruz County is not Santa Cruz County, rather simply Santa Cruz.  As such, it is unclear which value represents Santa Cruz County and which the City of Santa Cruz, as with Monterey County/City of Monterey, and so forth.  

As users need to be able to facet and distinguish between counties and municipalities, and given the variability of the of the labels available within the Geonames authority records, we've determined that the best path forward is to replace the labels on the Geonames URIs with local, customized labels.

### Acceptance criteria
**Done means:**
- [x] Identify Geonames URIs for counties in the DAMS and the aerials photos collection; supply recommended local labels
- [x] Replace Geonames labels with custom labels

**Comment by rmjaffe** [comment]
@snehagunduraoUL This one done?

**Comment by snehagunduraoUL** [comment]
Harry Mayo solr update is still running.

**Comment by snehagunduraoUL** [comment]
@rmjaffe This can be moved to done.
