### ISSUE TITLE
(2) resourceType value displays as URI

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#570]
### Describe the bug
In the QA of the aerials collection, it was observed that the URI supplied for resourceType is displaying instead of the label.

### Screenshots
<img width="1116" alt="Screen Shot 2023-02-15 at 12 33 21 PM" src="https://user-images.githubusercontent.com/32003407/219148029-8e1c33b4-fbf4-4538-9760-cd4cc2314930.png">

Type displays as: http://purl.org/dc/dcmitype/Image
Type *should* display as: Image

### Acceptance criteria
**Done means:**
- [ ] resourceType label displays in metadata records
- [ ] purl.org URI's are parsed to grab the label value and ingest it into the local vocabulary
- [ ] Future ingests can use plain text labels to ingest into the local vocabulary

### Related work
#418

**Comment by rschwab** [comment]
Note that the fix in the PR above does not fix existing labels. There are two ways for doing that:
1) Round tripping the works that have purl.org labels for resource Type
2) Deleting from ld_buffers database table all the records with label like '%purl%', then re-indexing or re-saving the works.

**Comment by rmjaffe** [comment]
@rschwab Perhaps is Monday's standup can you walk me through what option #2 entails?  Option #1 would basically involve round tripping everything in the DAMS.

**Comment by rschwab** [comment]
Both methods involve updating all the records that have an incorrect label, ie instead of "Image" displaying to users its displaying "http://purl.org/dc/dcmitype/Image".

In production and staging the incorrect labels aren't in the database. I'm pretty certain this was introduced in code only during the past few months when nothing was ingested into production or staging.

It's likely we don't need to fix the broken labels, as they are only in sandbox.

**Comment by rschwab** [comment]
This needs more work. [This test work](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/ft848r258/edit?locale=en) does not display the type appropriately, though the ID looks correct. [This other test work](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/cj82k810d?locale=en) created labels just fine.

It seems as if local authorities are not working in some circumstances. [This PR](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/499) attempted to solve a [slightly different issue](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/501), but may be related to this problem.

Here is an example URL for viewing all terms in a local vocab: http://digitalcollections-staging-sandbox.library.ucsc.edu/authorities/terms/local/dcmi_types

Other notes I took regarding all the existing local vocabs on sandbox:
```
"licenses"		not used in metadata.yml, legacy type
"resource_types" 	not used in metadata.yml, legacy type
"rights_statements"	not used in metadata.yml, legacy type
"dcmi_types"		empty in sandbox, weird id's in prod
"agents"		works
"places"		works
"time_periods"		empty in sandbox, 2 tests in prod
"topics"		works? (not currently used in metadata.yml)
"formats"		works?
"genres"		empty on prod, tests in sandbox

legacy:  ie: {id: "Article", label: "Article", active: true}
```

**Comment by rmjaffe** [comment]
@rschwab Just loaded a [small test set ](http://digitalcollections-staging-sandbox.library.ucsc.edu/collections/sb3978902?locale=en in sandbox with the following resourceType values:
http://purl.org/dc/dcmitype/Collection
http://purl.org/dc/dcmitype/Text
http://purl.org/dc/dcmitype/Image
http://purl.org/dc/dcmitype/MovingImage
http://purl.org/dc/dcmitype/Sound
http://purl.org/dc/dcmitype/StillImage

None of the URIs are displaying; all the records display the appropriate labels.  

Followed up by roundtripping the test set with labels vs. URLs as values in resourceTypes:  Those are displaying nicely too.  I think this is ready for production.

**Comment by rmjaffe** [comment]
This looks good in production too.
