### ISSUE TITLE
(2) Apply Interim Complex Object UI: Desktop

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#577]
### Descriptive summary
Apply new styling for parent objects to match mockup

### Background
![Web 1920 – 1](https://user-images.githubusercontent.com/6412857/220484328-ddae0326-955c-44bb-a2c2-9aa4d3877ecd.png)

### Acceptance criteria
**Done means:**
- [ ] Display the term "(Image Set)" after the parent title
- [ ] Change "About this item" to "About this set" for parent items
- [ ] Hide the Download button
- [ ] Do not display the file/image associated with the parent object

### Related work
#563

**Comment by rmjaffe** [comment]
Looks good!  Checking against this [small test set](http://digitalcollections-staging-sandbox.library.ucsc.edu/collections/br86b414d?locale=en), download button is not showing up on parent display but appears on children and single work displays. Likewise, no image is displaying on the parent page but loads on the single and child work displays.  Same for content in the aerials collection.

**Collection landing page**
![Screen Shot 2023-03-13 at 12 35 45 PM](https://user-images.githubusercontent.com/32003407/224813771-17e07bbe-f90c-4990-915d-c7bacf14f76c.png)

**Parent work page**
![Screen Shot 2023-03-13 at 12 35 59 PM](https://user-images.githubusercontent.com/32003407/224813802-4cd3af67-4f79-41c0-973f-1e38c9dee7d8.png)

**Child work page**
![Screen Shot 2023-03-13 at 12 36 12 PM](https://user-images.githubusercontent.com/32003407/224813838-535e8917-c344-4958-bad0-6d532e991402.png)

**Single work page**
![Screen Shot 2023-03-13 at 12 36 27 PM](https://user-images.githubusercontent.com/32003407/224813870-483ab482-1925-4453-9a0d-358bcc845c3c.png)

**Comment by rmjaffe** [comment]
Everything is as expecting in production.

**Comment by JessWaggs** [comment]
Looks good to me!
