### ISSUE TITLE
(2) Apply new Interim Complex Object styling: Mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#578]
### Descriptive summary
Apply new styling for parent objects to match mockup

### Background
![iPhone X-XS-11 Pro – 1](https://user-images.githubusercontent.com/6412857/220486019-06328c42-ba3d-406c-9e31-2e696ce47ef8.png)

### Acceptance criteria
**Done means:**
- [ ] Display the term "(Image Set)" after the parent title
- [ ] Change "About this item" to "About this set" for parent items
- [ ] Hide the "About this item" content 
- [ ] Make "About this set" clickable to display the hidden metadata
- [ ] Hide the Download button
- [ ] Do not display the file/image associated with the parent object

### Related work
#577 
#564

**Comment by rmjaffe** [comment]
I have no way to check this as my phone is complete disconnected from the UCSC universe.

**Comment by snehagunduraoUL** [comment]
@rmjaffe you could test the mobile display from your browser too. 
1. Go to customize and control google chrome 

![Image](https://user-images.githubusercontent.com/92340457/225151316-9e7120c0-f8d2-43b7-abc3-1b98811cbefa.png)

2. Click on More Tools -> Developer Tools
3. Find this Mobile device symbol on the top right. Click on it.


![Image](https://user-images.githubusercontent.com/92340457/225152882-c9ab0f3c-6fc3-4e71-be55-948d8d6abd2c.png)

**Comment by rmjaffe** [comment]
@snehagunduraoUL THANK YOU!!

I just looked at these changes in mobile view and things look good. Of the acceptance criteria, I think these item are done:
- [x] Display the term "(Image Set)" after the parent title
- [x] Change "About this item" to "About this set" for parent items
- [x] Hide the Download button _(on parent display page presumably)_
- [x] Do not display the file/image associated with the parent object

I have questions about these items:
- [ ] Hide the "About this item" content 
- [ ] Make "About this set" clickable to display the hidden metadata

_I'm seeing the top portion of the item metadata record appear per usual on the parent and child work display pages.  "About this item" and "About this set" do not appear as clickable links to me.  Examples:_

**Parent**
![Screen Shot 2023-03-14 at 3 36 16 PM](https://user-images.githubusercontent.com/32003407/225158358-06d9af3c-56c3-434a-ac2b-9f796aa94c66.png)

**Child**
![Screen Shot 2023-03-14 at 3 43 37 PM](https://user-images.githubusercontent.com/32003407/225158500-e291263b-d2cd-4c19-9568-1830f9056a88.png)

**Comment by rmjaffe** [comment]
Weird!  In looking at the mobile view in another browser, the "About this set" on the parent display pages is linked and the metadata hidden:

![Image](https://user-images.githubusercontent.com/32003407/225159090-2d0114f2-650e-4405-b637-6ad330cac981.png)

**Comment by snehagunduraoUL** [comment]
Are the previous screenshots on Mobile view?

**Comment by rmjaffe** [comment]
Yes.  Perhaps the dimensions were different on each view?

**Comment by JessWaggs** [comment]
This looks good to me on mobile! It meets all of the acceptance criteria listed in this ticket.

(Though it does make me realize we have some other mobile styling issues I'd like to tackle in the future : )

**Comment by rmjaffe** [comment]
I didn't note this on sandbox because I didn't think to open up the "About this set" metadata, but when I do in production, I'm only seeing the top portion of the parent metadata record with no option to expose the full record.

**Before**
![Image](https://user-images.githubusercontent.com/32003407/225451397-a852fc3e-7ea5-43c4-932f-69aa33ba402a.png)

**After**
![Image](https://user-images.githubusercontent.com/32003407/225451501-238671b1-6006-4bc9-930f-04774bef094a.png)

**Comment by JessWaggs** [comment]
I found an interesting bug that I'll file a separate ticket for, but I think it's pretty low priority because I only see it when I resize the browser window from mobile-size to desktop, and I doubt typical users are doing that.

Other than that, looks good! I'm not seeing the issue Rachel found on my devices.
