### ISSUE TITLE
(2) Apply Interim Complex Object search results styling

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#579]
### Descriptive summary
Apply new styling to match mock up

### Background
![SearchResults](https://user-images.githubusercontent.com/6412857/220486743-6b26f8d8-1bd9-4d9e-a5fc-210a48ee3323.png)

### Acceptance criteria
**Done means:**
- [ ] Parent work in a search results set displays the thumbnail of the representative image on the results page
- [ ] Complex objects in a search result set display the addendum text "(Image Set)" after the title (or truncated title on the results page)
- [ ] Thumbnails for complex objects in search results sets display a multiple file icon in the lower right corner

### Related work
#569

**Comment by JessWaggs** [comment]
![noun-files-116439-676767](https://user-images.githubusercontent.com/6412857/220486994-2422b125-9603-40d6-a691-97c78179fefa.png)

**Comment by rschwab** [comment]
@JessWaggs this is ready for QA on sandbox along with #577 and #578.

**Comment by snehagunduraoUL** [comment]
@JessWaggs Could you please confirm if this can be moved? Thanks.

**Comment by JessWaggs** [comment]
@snehagunduraoUL Yes - looks good!

**Comment by rmjaffe** [comment]
Looks great in production!

**Comment by JessWaggs** [comment]
Looks good!
