### ISSUE TITLE
RMB metadata display

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#60]
Some metadata elements are failing to display:  subject properties, description, collectionCallNumber, and boxFolder.  May be worth checking on titleAlternative too.

As was previously decided, collectionCallNumber and boxFolder need to display together within a single display field, e.g.:

collectionCallNumber  (MS 20) + boxFolder  (Box 464) = collectionCallNumber, boxFolder (MS 20, Box 464)

**Comment by NedHenry** [comment]
Thanks Rachel! I believe this is part of a bug in how my ScoobySnacks gem
is modifying Hyrax's configuration of Blacklight. It is a little more
complicated than it needs to be, but I can at least have the metadata
displaying very soon.
Best!
Ned

**Comment by rmjaffe** [comment]
Cool.  I think having the elements display is key -- the customization of the combined collectionCallNumber+boxFolder thing I think can wait.  Thanks :)

**Comment by NedHenry** [comment]
Noted! That's not the hold-up at the moment.

**Comment by NedHenry** [comment]
I believe I fixed this with the following commits: 11377414e40c837b58993de9b55db40c38d9ab67 and 4bdbadaf1c4e5bbb70d2768858a021a3b3877281

These issues were the result of me trying to be clever customizing the metadata display. I need to fix my customizations and re-deploy them when they work consistently.
