### ISSUE TITLE
(2)Aerial photo representative images not diplaying

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#631]
The collection landing page for the aerial photo flights (image sets) are not displaying the correct image for a few different works: 

Issue: The representative thumbnail for the image set on the landing page for the 1928a flight should be 1928a_index_geo_key.tif.  Right now it is 1928a_09a.tif.

Issue: The representative thumbnail for the fileset on the landing page for the 1949 flight should be 1949_bux_index_geo_key.tif.

Issue: The representative thumbnail for the fileset on the landing page for the 1956-B flight is showing a generic file icon, it should be 1956b_abg_index_geo_key.tif.  Also - this one does not specify that it is an image set like the other works in the aerial photo collection.

**Comment by snehagunduraoUL** [comment]
1956-B was still running during QA is my guess. The thumbnail displays correctly now. 
1928-A and 1949 flight thumbnails have been fixed.
https://digitalcollections.library.ucsc.edu/collections/5t34sp24c?locale=en
