### ISSUE TITLE
(1) Aerial photo flight 1963-E

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#636]
The parent work for the 1963-e aerials flight (https://digitalcollections.library.ucsc.edu/concern/works/s4655m883?locale=en) is showing the generic cube object as the representative image.  None of the child works are displaying.  It was part of the aerials_12 ingest spreadsheet and should have 327 child works.

**Comment by rmjaffe** [comment]
Aerial_12 has been reloaded.  [1963-E ](https://digitalcollections.library.ucsc.edu/concern/works/s4655m883?locale=en)looks as it should. @chesleyperry Can you confirm?
