### ISSUE TITLE
(5) Re-order flights on Aerials collection landing page

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#642]
### Describe the bug
Presently the flights within the aerial photographs collection display on the [collection landing page](https://digitalcollections.library.ucsc.edu/dashboard/collections/5t34sp24c?locale=en) in the order that they were ingested into the DAMS.  We want to re-order them to display in order from oldest (1928) to most recent (2003).

### Acceptance criteria
**Done means:**
- [ ] Aerial flights/works are listed from earliest to most recent

**Comment by rschwab** [comment]
There currently is not a way to order the children of a parent in Hyrax. This will have to be a feature we implement, then do round trips to add the order values to the desired collections.

**Comment by rmjaffe** [comment]
@rschwab Yep -- child works are fine.  We'd like to flights as they appear on the collection landing page (see below) to be reordered if possible.  This came up before in a standup and if I recall, it seemed that it may be doable.
![Screen Shot 2023-04-18 at 11 32 27 AM](https://user-images.githubusercontent.com/32003407/232870900-f5513b2f-dd7b-442b-b5db-a26c4a0bb4d4.png)

**Comment by rmjaffe** [comment]
I'm guessing this would basically involve somehow making the date sorted version the default display version:

![Image](https://user-images.githubusercontent.com/32003407/232871960-f17fe257-e895-4b8f-a7ec-bcfc976f9b3d.png)

**Comment by chesleyperry** [comment]
If you sort alphabetically, the dates display correctly.  This can be handled by updating the URL: if you use this address (https://digitalcollections.library.ucsc.edu/dashboard/collections/5t34sp24c?utf8=%E2%9C%93&sort=title_ssi+asc&per_page=100&locale=en), it sorts alphabetically ascending and displays 100  published flights, which is all of them.  I don't know how much work this might be to change for one collection.
@JessWaggs do you have any thoughts on this?

**Comment by snehagunduraoUL** [comment]
@chesleyperry do we need that feature just for the aerials?

**Comment by chesleyperry** [comment]
@snehagunduraoUL - Yes I think so. The aerials are a little unique.

**Comment by rmjaffe** [comment]
@snehagunduraoUL @chesleyperry Can we wait to take action on this until there's a opportunity to discuss as a team (perhaps in our standup next Wednesday)?

**Comment by chesleyperry** [comment]
Yes - that's fine with me.

**Comment by rmjaffe** [comment]
@snehagunduraoUL Reordering looks good!

**Comment by snehagunduraoUL** [comment]
Thanks for the QA Sue and Rachel. Moving this to staging/production.

**Comment by rmjaffe** [comment]
Just had a look at this on production -- as the aerials are private, can't see the re-ordering in the public view, but I had a look at the Cabrillo Music Festival recordings.  Those have been reordered, but they appear most recent (1990) on page 1 through oldest (1965) on page 10.  Would prefer for that order to be reversed:  oldest (1965) appearing on page 1 and move forward through the collection as you page through the results.

**Comment by snehagunduraoUL** [comment]
@rmjaffe [Here](https://digitalcollections.library.ucsc.edu/collections/5t34sp24c?locale=en) is the public view of Aerials. You can navigate through dashboard to see the public view of a private collection. 
Also, this sorting feature is done only for Aerials. 
Was the  Cabrillo Music Festival recordings not sorted previously and now the order is different?

**Comment by snehagunduraoUL** [comment]
Yes. Do we want the sorting for all collections? Or just Aerials and Cabrillo?

**Comment by rmjaffe** [comment]
For the other ones, it doesn't matter.  Just aerials and Cabrillo.  Thank you :)

**Comment by snehagunduraoUL** [comment]
Okay. I will make the change and let you know.
