### ISSUE TITLE
(2) Update aerials thumbnail images

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#643]
### Describe the bug
The thumbnails on a handful of the aerials flights need to be updated to show the first child work.  Includes:

1967-A
1967-C
1967-B
1967-E
1967-M
1967-K
1968-D
1968-A
1968-B
1969-A
1969-B
1969-C
1969-D
1969-G

### Acceptance criteria
**Done means:**
- [ ] Thumbnails match first child works

**Comment by snehagunduraoUL** [comment]
@rmjaffe all the thumbnails have been updated to show respective first child work.
https://digitalcollections.library.ucsc.edu/collections/5t34sp24c

**Comment by rmjaffe** [comment]
Looks good!  Thank you
