### ISSUE TITLE
(3)Aerials genre value chaos

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#644]
### Describe the bug
The values supplied for genre on the metadata spreadsheets are not consistent which is resulting in a pseudo-duplication of terms in the metadata display for some works.  Am also concerned that this will affect faceting.

The three values that appear in genre are:
http://id.loc.gov/authorities/genreForms/gf2011026032 = Aerial photographs
http://vocab.getty.edu/aat/300128222 = aerial photographs
http://id.loc.gov/authorities/genreForms/gf2011026530 = Remote-sensing images

Here are some examples:

**1) 1928-B**
Ingest metadata (Aerials_1)
![Screen Shot 2023-04-18 at 1 38 59 PM](https://user-images.githubusercontent.com/32003407/232899607-4e7f999e-d47e-4542-9eef-6293eb6ab548.png)

[Display](https://digitalcollections.library.ucsc.edu/records/37720h672)
![Screen Shot 2023-04-18 at 1 40 57 PM](https://user-images.githubusercontent.com/32003407/232899988-eeaad4da-4f27-4c4d-ac74-8ab4777d1823.png)

**2) 1928-B** 
Ingest metadata (Aerials_2)
![Screen Shot 2023-04-18 at 1 33 28 PM](https://user-images.githubusercontent.com/32003407/232900226-ec0cd506-6a18-4b5f-8585-ccd8813235f8.png)

[Display](https://digitalcollections.library.ucsc.edu/records/6h440x31s)
![Screen Shot 2023-04-18 at 1 45 02 PM](https://user-images.githubusercontent.com/32003407/232900844-855bfa12-b719-427d-93e0-63ea6ecf2ed1.png)

**3) 2003-L**
Ingest metadata (Aerials_21)
![Screen Shot 2023-04-18 at 1 46 55 PM](https://user-images.githubusercontent.com/32003407/232901178-7bf89548-a1ff-40c4-a88a-2adbca298012.png)

[Display](https://digitalcollections.library.ucsc.edu/records/3197xs17n)
![Screen Shot 2023-04-18 at 1 47 54 PM](https://user-images.githubusercontent.com/32003407/232901558-e677f441-1d65-44a9-99d7-6237dbe1fd1f.png)

### Background
This was my fear when the original spreadsheet was cut into 21 sheets -- that it's be harder to identify any variability in the data.  Unfortunately, my fear has come to pass and genre is a mess.  Ideally, every work in the collection should have two genre values:  http://id.loc.gov/authorities/genreForms/gf2011026032 = Aerial photographs & http://id.loc.gov/authorities/genreForms/gf2011026530 = Remote-sensing images.  

Thinking back to much earlier in the digital projects workflow, I'm guessing that we ended up with two versions of the original spreadsheet:  one that DI was working on and one that I was working on.  Pre-ingest, I used the one from DI's folder, but it seems that a number of the past metadata updates I made were not reflected on that DI source sheet, including to genre.

I don't know if there's a way to update/correct these values that does not involve running 21 round trips or stitching 21 spreadsheets back together again.

### Acceptance criteria
**Done means:**
- [ ] All works (parents & children) have the same two genre values:  http://id.loc.gov/authorities/genreForms/gf2011026032 = Aerial photographs & http://id.loc.gov/authorities/genreForms/gf2011026530 = Remote-sensing images
- [ ] Workflow issues that resulted in this issue have been discussed/addressed: versioning metadata spreadsheets, having to carve up collections for ingest, need for more than one metadata person

**Comment by rmjaffe** [comment]
Assessment of genre values: https://docs.google.com/spreadsheets/d/1UrmdFXs9fBgaNr50-bow8Y63aUrHMVta19Wip5mCUmc/edit?usp=sharing

**Comment by rschwab** [comment]
@rmjaffe This is ready for QA.

**Comment by rmjaffe** [comment]
Thanks @rschwab.  I looked first at the three flights given as example on this ticket:  parent and children for 1928-A and 1928-B look good; child works for 2003-L still include the Getty "aerial photographs" value:

![Screen Shot 2023-05-02 at 9 39 06 AM](https://user-images.githubusercontent.com/32003407/235729759-d3af1506-21b0-41a3-a10e-e764c51443fb.png)

https://digitalcollections.library.ucsc.edu/records/hx11xm37n

I then checked parent and child metadata on a couple flights from each of the ingest spreadsheets that were indicated as needing updating:

Aerials_1 OK
Aerials_12 OK
Aerials_13 OK
Aerials_14 OK
Aerials_15 OK
Aerials_16 OK
Aerials_17 OK
Aerials_18 OK
Aerials_19 OK
Aerials_20 OK
Aerials_ 21: 2001 = OK, 2003-L = checked 10 child works all were OK except that shown above as the example!

I think the only thing that needs to be done is to remove that extraneous value from https://digitalcollections.library.ucsc.edu/records/hx11xm37n

**Comment by rmjaffe** [comment]
Just went to the edit form for that work (https://digitalcollections.library.ucsc.edu/records/hx11xm37n) to remove the extraneous genre value and was reminded that the work on the edit form was pushed back to Planning, but wanted to call out Ned's tooltip for populating the genre property:  "Ex. lectures; underground dance music."  Underground dance music ... ?

![Image](https://user-images.githubusercontent.com/32003407/235754957-b0f4cba1-5a3a-408f-8363-f69b3bace97d.png)

Will need to roundtrip to correct values on that image.

**Comment by rschwab** [comment]
Hmm I saw this on some of the earlier sheets I worked on and thought it had to do with inheritance. It might be that the timing was off, ie the child work updated and inherited before the parent work was corrected. I'll re-run the aerials21 sheet and that should hopefully fix it.

**Comment by rschwab** [comment]
@rmjaffe Running the import again and updating metadata fixed the issue on the work you found. I'm also running the aerials 20 sheet again just for good measure. Let me know if you find any others.

**Comment by rmjaffe** [comment]
Looks good -- not seeing the errant Getty value on https://digitalcollections.library.ucsc.edu/records/hx11xm37n.  Looked at a selection of aerials works (1928-A, ones flagged as needed the genre values updated, ones not needing updating) and they look as they should!
