### ISSUE TITLE
(2) Variation in relatedResource property

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#645]
### Describe the bug
Originally, the related resource information for all the works in the collection read, "Aerial photo guide: https://guides.library.ucsc.edu/maps/aerial"  as that text prefix was cause in errors, it was remove from the ingest spreadsheets and only the URL was ingested.  That said, the relatedResource value in 1928-F, 1931-B, 1931-D and I'm surmising the other aerials_3 flights reads: "Aerial photo guide: https://guides.library.ucsc.edu/maps/aerial".

![Screen Shot 2023-04-18 at 4 14 14 PM](https://user-images.githubusercontent.com/32003407/232924643-12bd5ebf-3848-490a-9a75-818cd7c02bc6.png)

### Acceptance criteria
**Done means:**
- [ ] relatedResource value on all works in the aerials collection should be URL only.

### Related work
Aerials about this collection link is broken #632

**Comment by rschwab** [comment]
@rmjaffe This is ready for QA.

**Comment by rmjaffe** [comment]
Checked parent and child works on 1931-F, 1931-B, 1928-H and 1928-F.  Looks good!
