### ISSUE TITLE
subjectName

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#65]
The value "Gomez, Joe" (assigned to images in the subseries, "Joe Gomez illustrates Avalon Ballroom poster (Big Brother and the Holding Company and Mount Rushmore, November 25-27, 1967)") is displaying across the collection in all of the metadata records.

**Comment by NedHenry** [comment]
Thanks for noticing this, Rachel. Fixing it now.

**Comment by NedHenry** [comment]
This was fixed months ago, but the issue wasn't closed at the time. Closing it now.
