### ISSUE TITLE
Aerial photos: problematic images

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#651]
### Describe the bug
Some of the images in the aerials collection aren't loading correctly.  I suspect this is not a display/UV issue but is rather and ingest/image processing issue.

Examples:
1966-D : https://digitalcollections.library.ucsc.edu/records/fn107341x
1967-M: https://digitalcollections.library.ucsc.edu/records/8k71np053
1976-77 Color: https://digitalcollections.library.ucsc.edu/records/f1881r39c

### Expected behavior
Images should display in full.

### Acceptance criteria
**Done means:**
- [ ] Affected image identified
- [ ] Images display correctly.

### Related work
#418

**Comment by rmjaffe** [comment]
As a next step @afrebert @chesleyperry @rmjaffe will each thoroughly QA a couple flights in production noting the filenames for any problematic images.

**Comment by rmjaffe** [comment]
1985-C (59 images): [1985c_853012_4-07.tif](https://digitalcollections.library.ucsc.edu/records/kh04dv58t)

**Comment by chesleyperry** [comment]
1949 
[1949_bux_10f-087.tif](https://digitalcollections.library.ucsc.edu/concern/works/p5547w22q?locale=en)

**Comment by afrebert** [comment]
1928 A through H: clear

**Comment by rschwab** [comment]
Problem files are all the 800px wide derivatives. As a stopgap measure, we'll try #652

**Comment by rschwab** [comment]
I've found another example of a broken image, this one from the Universal Viewer loading a 799px image. These images can be found in the Cantaloupe cached images folders, so I believe this is an intermittent error in Cantaloupe.

**Comment by rmjaffe** [comment]
@chesleyperry @afrebert  #652 in in production QA and it looks like it has resolved the image display issue for the aerials.  Mind having a look at a few of the 'problem' images to confirm that they now look OK?

**Comment by chesleyperry** [comment]
I have looked through about 25 images and they all look great!  No issues.

**Comment by chesleyperry** [comment]
Most of the images seem to be fixed.  Photos in flight 1931-D still display the rectangular white box if I click to view the image in the universal viewer.  Viewing the image in full screen, zooming in or out makes the box disappear.
Examples: All images in this flight have this problem (as far as I can see)
[1931-D Santa Cruz County Flight C-1550](https://digitalcollections.library.ucsc.edu/records/q811kp156)
Here's a link to a single image:
[1931-D Santa Cruz County Flight C-1550 34](https://digitalcollections.library.ucsc.edu/concern/works/k0698c41b?locale=en)
