### ISSUE TITLE
(1) Change default image size to 1000px derivative

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#652]
Change the default derivative displayed on works to 1000 pixels, currently its 800. The display will remain unchanged because the images are bound by CSS rules to max-height 600px, so only the underlying image size will be slightly larger.

**Comment by rschwab** [comment]
@rmjaffe @afrebert this is now in Sandbox. [This collection](http://digitalcollections-staging-sandbox.library.ucsc.edu/collections/0k225b067) has images that can be used for testig, many of the others don't have images attached.

**Comment by rschwab** [comment]
Thanks @rmjaffe! This morning I looked over this issue some more, and noticed [we aren't caching the 1000px size](https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/e2e28f8d869e52aeba2b15c50b4104f42393fd15/app/models/file_set.rb#L61-L66), which surprised me since we're using that as the 'download' size. I think we should probably change that as part of this ticket. 

Then, actually getting the server to cache 1000px for all our images would require a re-index of the site. Since we've noticed some other performance issues, we might consider prioritizing that work before doing a re-index. I believe that work involves moving some of the new information related to image sets and child works into the solr document for the objects, work I'd currently rate at about a 3 pointer.

**Comment by rmjaffe** [comment]
@rschwab If it wasn't clear in the standup, yes, if it's feasible, let's knock out the other performance issues.  It'd be nice to have the aerials up and running more like hares instead of snails.

**Comment by rmjaffe** [comment]
Two more questions:  1) should we create new ticket for the performance improvement work?  2) if that work involves adding info about relationships to the solr doc, might that resolve the issue you found with the 86/86 flight, #653 ?

**Comment by rschwab** [comment]
Yes, I'll create a ticket for the performance issue. I don't think it will resolve the relationships issue though, because its only adding a few things to the solr doc: (1) does this object have children?, (2) is this object an image?, (3) is this object an audio file?. That other problem is more to do with saving the relationships in Fedora.

**Comment by rmjaffe** [comment]
This seems to have corrected the issue we were seeing with the aerials images.  Admittedly not exactly a comprehensive review, I looked at few images from a 3-4 other collections and it doesn't look like anything non-aerials as negatively impacted.
