### ISSUE TITLE
(2) Aerials 86/87 relationships not working

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#653]
The [1986-87 Color Central California Coastline Flight](https://digitalcollections.library.ucsc.edu/concern/works/gx41mp756?locale=en)  from aerials sheet 20 doesn't have all its children attached. For example, [CC-APU-C 28](https://digitalcollections.library.ucsc.edu/concern/works/kd17cz447?locale=en), but there are many more.

I've tried running [an import to fix this](https://digitalcollections.library.ucsc.edu/importers/100?locale=en), using the required fields + parent. For parent I've tried both the bulkrax ID and the hyrax ID for the parent work, but neither seems to work.

**Comment by rschwab** [comment]
Trying to delete this flight and re-ingest it.

**Comment by rschwab** [comment]
@rmjaffe The re-ingest seems to have worked. I see 434 children on the flight.

**Comment by rmjaffe** [comment]
Thanks @rschwab, I'll check this out this afternoon.

**Comment by rmjaffe** [comment]
In comparing what's in production to what's on the spreadsheet, I think this is resolved.  Thanks!
