### ISSUE TITLE
genreForm (Physical Description) not displaying for RMB

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#66]
Physical Description is not displaying in the RMB metadata records.  If this is a display issue, I don't see this holding up the Calisphere go-live.

**Comment by NedHenry** [comment]
I just clicked on a random record, and I do see physical description
displayed:
http://digitalcollections.library.ucsc.edu/concern/works/rj430457n

Can you link to one where it is not displayed?

**Comment by rmjaffe** [comment]
Sorry for the confusion, my mistake -- that should be genreForm (Physical Format)

So in looking at the record, we're seeing "Physical Description: 35 mm" aka physicalDescription, but "Physical Format: Black-and-white negatives" aka physicalFormat isn't visible.  Thanks for asking.
