### ISSUE TITLE
(5) Fix rvm on staging + production

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#660]
Production and staging servers appear to not be set up to use the correct versions of ruby as managed by rvm. On both servers, rvm info shows the path as `/home/sufia/.rvm` but the which ruby command returns `/bin/ruby`. So while rvm is installed and has been updated, the application is still using an older ruby version.

Sandbox has the correct configuration:
rvm info shows path as `/usr/local/rvm` 
which ruby shows `/usr/local/rvm/rubies/ruby-2.7.2/bin/ruby`

**Comment by snehagunduraoUL** [comment]
on production


![Image](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/92340457/625da8fa-1c5d-42a8-ac6f-20558e2a8a44)

**Comment by rschwab** [comment]
No it was me missing something: rvm is installed not globally but per user. My bad! Thank you Sneha, I'll close this one.
