### ISSUE TITLE
Banner or alert to notify maintenance

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/ucsc-library-digital-collections#685]
Develop a UI banner/alert to notify patrons that the collection is under maintenance or the application is going through the deployment/maintenance and some services/collections might be unavailable.

**Comment by rschwab** [comment]
@JessWaggs @rmjaffe Here's a screenshot of the current pull request for your review:

![Firefox_Screenshot_2023-11-03T20-47-23 762Z](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/515412/d4a0421f-ef6f-436c-9252-d44b5ce4d537)

**Comment by JessWaggs** [comment]
This looks good!

**Comment by rschwab** [comment]
[PR 686](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/686)

**Comment by rschwab** [comment]
Did some QA on production. Here's the screenshot of the code in place:


![Image](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/515412/c73d33b6-b4eb-4c91-9df3-b916f40952d5)


The "" makes the alert a code comment instead, removing that makes it live. Screenshot of that:


![Image](https://github.com/UCSCLibrary/ucsc-library-digital-collections/assets/515412/c805648a-9373-4469-80d9-0e218759aba6)

**Comment by snehagunduraoUL** [comment]
Thanks for QA Ryan! Can this one be closed?

**Comment by rmjaffe** [comment]
Same question from me!

**Comment by rschwab** [comment]
Yep!
