### ISSUE TITLE
Reviewer user accounts for Scott and Ann

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#75]
Hi Ned,

Can you give permissions in the DAMS for Ann Hubble (ahubble@ucsc.edu) and Scott Campbell (scamp@ucsc.edu) to review items?  I will have them use the signup link on the login screen to create the accounts.

Thanks, Sue

**Comment by chesleyperry** [comment]
It looks like Scott is all set but Ann doesn't have permissions to review items.

**Comment by NedHenry** [comment]
Thanks! I'll set Ann up now. Let me know if Scott reports any issues (he's
the first to use the review-only permissions I think).
