### ISSUE TITLE
Physical Format uri showing foreign language text

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#76]
Items in the RMB/PJ collections with physical format = color transparencies are showing up with foreign language text in the physical format field in the DAMS.  
Here's an example of a link:
http://digitalcollections.library.ucsc.edu/concern/works/j6731409k?locale=en

Physical Format is displaying: cǎi sè tòu míng piàn

In the spreadsheet, the uri for physical format for those item is http://vocab.getty.edu/aat/300128364

I'm guessing it's a linked data issue?

**Comment by NedHenry** [comment]
Thanks for reporting this, Sue. It is indeed a linked data issue. It is one
that we saw on previous ingests, but was never fully resolved. In some
cases Hyrax's linked data services are pulling in labels in arbitrary
languages from our URLs. This is a bug in Hyrax, but it is one that we can
and should fix ourselves (though I have not yet done so). For now, please
report this type of issue when you see it. I should be able to quickly
correct the labels collection by collection.

**Comment by NedHenry** [comment]
Fixed
