### ISSUE TITLE
Audio recordings not playing 

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#79]
Hi Ned,

The audio recordings for the Development of Western Civilization aren't playing right now.  Can you look into it?

**Comment by NedHenry** [comment]
Yes, I will look into this tomorrow.

**Comment by chesleyperry** [comment]
Hi Ned,

I'm just nudging this a little - we have one vocal patron interested in the Hitchcock recordings.  Do you have a time frame for the fix?

Thanks,  Sue

**Comment by NedHenry** [comment]
Thanks for the nudge, Sue. I will get this fixed by tomorrow evening. I am
leaving on vacation for two weeks starting Friday, and this should get
fixed before I leave. Let me know if there is anything else urgent I need
to get done before then.
All the best,
Ned

**Comment by NedHenry** [comment]
I believe this is fixed with commit aab60b0b62faa01e37708a7a50b6eae106bd2406
I just displayed the mp3 derivative using our own medialelement skin, and skipped the HLS streaming for these lectures for now.
