### ISSUE TITLE
Issues with several individual files for Hitchcock recordings

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#81]
Several works in the 1976-77 History of Western Civ collection are not playing on the object pages. Not playing means, I hit play and nothing happens. In the multiple track player on the main page, the wrong lecture plays when one of these records is selected.  My suggestion is to unpublish the problematic recordings and troubleshoot them later.  When I hit the edit button on those works, the system displays the error message: "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."
Example url:
http://digitalcollections.library.ucsc.edu/concern/lectures/4t64gn212/edit?locale=en

**Comment by chesleyperry** [comment]
The problematic works are:
Track 3 (plays GD answering machine) http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/4t64gn212

Track 13 (doesn't play, displays object icon instead of audio icon)
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/3197xm063

Track 14
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/z603qx43s
Track 15
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/1c18df79x

Track 16
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/4f16c2831

Track 23
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/h702q641c

Track 24
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/ww72bb527

Track 25
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/6q182k13s

Track 26
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/2z10wq25s

Track 27 (plays, not Hitchcock though)
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/4x51hj03c

Track 31
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/q524jn78d

Track 32
http://digitalcollections.library.ucsc.edu/concern/parent/sx61dm30x/lectures/r494vk192

**Comment by NedHenry** [comment]
Many of these tracks were deleted and re-ingested from scratch, breaking the links above. However, I just looked through the 1970s Hitchcock lecture and played the first few seconds of each of the lectures mentioned above. They all sounded like valid hitchcock lectures, with running times near 50 minutes (but not identical to one another). I believe this problem is solved.
