### ISSUE TITLE
Review Submissions in Workflow is down

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#82]
When we try to access the Review submissions function from the Tasks section of the Dashboard, we get the error message: "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

http://digitalcollections.library.ucsc.edu/admin/workflows?locale=en

**Comment by NedHenry** [comment]
Fixed in d10f6e762cd1b42075718947e7589c859d1af179
Thanks for reporting this. Let me know if there are more problems.
