### ISSUE TITLE
Unable to "edit" records in Hyrax

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#83]
When I attempt to edit a record in the DAMS, right now I get the error message: We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Here's an example of the url that returns the error: http://digitalcollections.library.ucsc.edu/concern/works/z603qx948/edit?locale=en

I'm trying to unpublish the problematic Hitchcock audio files so can delay fixing the player and files for that collection for now.

**Comment by NedHenry** [comment]
I will look into the issue with the "edit" page asap. Thanks

**Comment by NedHenry** [comment]
Fixed! A custom class was autoloading in my development environment, but failing to load in the production environment. That's a symptom that I should be spending more time on automated tests of my code. In any case, let me know if any of this stops working again :/
