### ISSUE TITLE
Digital Filename metadata element not displaying

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#91]
With the last upgrade, the digital filename metadata element is no longer displaying on the work full display page (example: http://digitalcollections.library.ucsc.edu/concern/works/5d86p0780?locale=en).  We need to see this element in order to process Special Collections reproduction requests.  If is something you can restore?

Thanks,  Sue

**Comment by NedHenry** [comment]
This has been fixed as a general problem, but let me know if you see any particular items for which this metadata doesn't display please report it. That item could need reindexing. I believe that I have verified that all items in the system are currently indexed correctly.
